### ISSUE TITLE
Youtube videos lightbox gallery - no next / previous controls

### ISSUE THREAD

**Issue by adskiremote** [ashleydw/lightbox#102]
Hi - seems that having a YouTube gallery doesn't let you move between next and previous (like you can with an image gallery).

I put data-parent in the top container on my page and still doesn't seem to work.  My code is as follows...

    	<div class="row">
				<div class="col-md-6">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">Panel title</h3>
						</div>
						<div class="panel-body">
							<div class="embed-responsive embed-responsive-16by9">
								<a href="http://www.youtube.com/watch?v=k6mFF3VmVAs" data-toggle="lightbox" data-gallery="youtubevideos" data-type="youtube">
									<img src="//i1.ytimg.com/vi/yP11r5n5RNg/mqdefault.jpg" class="img-responsive">
								</a>
							</div>
						</div>
						 <div class="panel-footer text-center">Click to play</div>
					</div>
				</div>

				<div class="col-md-6">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">Panel title</h3>
						</div>
						<div class="panel-body">
							<div class="embed-responsive embed-responsive-16by9">
								<a href="http://youtu.be/iQ4D273C7Ac" data-toggle="lightbox" data-gallery="youtubevideos" data-type="youtube">
									<img src="//i1.ytimg.com/vi/iQ4D273C7Ac/mqdefault.jpg" class="img-responsive">
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>

**Comment by ashleydw** [comment]
Does this work for you? http://ashleydw.github.io/lightbox/#youtube-gallery

**Comment by ashleydw** [comment]
no response

**Comment by JoergPf** [comment]
I would like to reopen this:
The example doesn't seem to show left-right-arrows for videos. 

It would be really great to have them. Is there a more precise example than http://ashleydw.github.io/lightbox/#navigateTo, how to achive this?

**Comment by ashleydw** [comment]
Correct that the example doesn't have the visible navigation icons - the overlay that would be required to show the navigation arrows would block the video player from being interacted with. Left/Right keyboard arrows still work.

If you need arrows, you could use `onNavigate` event and call `this.modal_arrows.css('display', 'none');`

**Comment by JoergPf** [comment]
Thanks - I just used a bit of css now, maybe someone else might find this useful:

```
.ekko-lightbox-nav-overlay{
	display: block !important;
	opacity: 1 !important;
	height: auto !important;
	top: 102%;	
}

.ekko-lightbox-nav-overlay a{
	opacity: 1 !important;
	width: auto !important;
	text-shadow: none !important;
	color: #3B3B3B;
}

.ekko-lightbox-nav-overlay a:hover{
	color: #20507D;
}

.modal-body {
    padding: 0px 0px 50px 0px !important;
}
```

**Comment by scriptgeni** [comment]
Great!, by just adding the css the arrows are now visible, but how can I center the arrows in the middle of the modal window.
