### ISSUE TITLE
not working arrows on mouse click

### ISSUE THREAD

**Issue by tkapler** [ashleydw/lightbox#103]
I love this plugin, but it drives me crazy, that i am unable to make working the gallery functionality with mouse click on arrows. I can use arrows on my keyboard, and it works perfectly, but when i click the arrow using mouse, nothing happens (or only the page on the background jumps up, so that the "#" href of the arrow is working, but not the action).
I do not know where can be a problem and how to analyse it (i am not skilled js/jquery programmer). I guess that maybe i should be able to use onNavigate, but i do not know how, there is no info about it.
My code is not anyhow special (just that i am on wordpress so i have to use jQuery instead of $ and that i am using font awesome icons

```
    jQuery(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
    event.preventDefault();
    jQuery(this).ekkoLightbox({
						always_show_close: true,
            left_arrow_class: 'fa fa-chevron-left',
            right_arrow_class: 'fa fa-chevron-right',
					});
});
```

and my html looks like
```
<a href="http://groupeseb-download.cz/wp-content/uploads/CF3610_high.jpg" data-toggle="lightbox" data-remote="http://groupeseb-download.cz/wp-content/uploads/CF3610_high-1024x446.jpg" data-gallery="gallery"><img src="http://groupeseb-download.cz/wp-content/uploads/CF3610_high-250x109.jpg" /></a>
```
(but i think my code is right, as the gallery works with keyboard, the problem is only the mouse).

any idea?
You can see it on http://groupeseb-download.cz/product/gc702d34/# (you will need username and password - both is "test")

**Comment by ashleydw** [comment]
Are you talking about the ones at the bottom of the page? They are missing the `data-gallery` attribute that you have in the above code.

**Comment by tkapler** [comment]
yes, sorry i have put it to production, so i have put the data-gallery off, but now i have placed there the condition for this user only, so you can see it live again

**Comment by ashleydw** [comment]
You're missing the `.` in your class names:

```jQuery(this).ekkoLightbox({
						always_show_close: true,
            left_arrow_class: 'fa fa-chevron-left',
            right_arrow_class: 'fa fa-chevron-right',
            gallery: 'gallery',
            gallery_parent_selector: '#gallery'
					});
});```

**Comment by tkapler** [comment]
oh, you are livesaver :-). i have thought that when it is name "class" than there should be a class name(s) not a selector.

**Comment by aero-sim** [comment]
I think i have the same problem, but your solution is not online so i could not exactly compare your solution. Maybe somebody can take a quick look? I just fail to find my mistake: http://vickymawiva.bplaced.net/portfolio/gallery/html/gallery2014.html

**Comment by ashleydw** [comment]
@aero-sim you haven't included the ekko css (404)

**Comment by aero-sim** [comment]
Thank you! That was even for me stupid! sometimes you just don't watch out for the easiest reasons...
