### ISSUE TITLE
Bootstrap-Sass v 3.4.4.1

### ISSUE THREAD

**Issue by upngo** [ashleydw/lightbox#104]
I recently updated my boostrap-sass gem to 3.4.4.1 and found a new rule has been added 
``` 
.modal-dialog 
{
    z-index: 1040;
}
```

This results in the modal box being behind the shaded overlay (which is suppose to hide only the current page so the modal pop up stands out)

My "patch" for this was to add a rule into the lightbox code

```
.modal-backdrop
{
    z-index: initial;
} 
```

**Comment by ashleydw** [comment]
Are you seeing this?

#86
#85 

http://stackoverflow.com/questions/10636667/bootstrap-modal-appearing-under-background

**Comment by upngo** [comment]
Yes it looks like the stackoverflow image.

My html layout is the same as the bootstrap site (so the top rated fixed on s/o was not relevant)
and I haven't got any custom css except for your lightbox code.

Everything works fine on a revert to bootstrap-sass 3.3.3

**Comment by ashleydw** [comment]
Do you have an example page?

**Comment by upngo** [comment]
I tried creating one but need to have a cdn for lightbox (github is not a cdn and sends mime type text/html but jsfiddle has strict mime checking so won't run it).
The port I'm talking about should be the same as the latest version of bootstrap 3.3.4

**Comment by jamin87** [comment]
I had this same problem but I think I've found out why.

It looks like they changed out the z-index works slightly. You just need to add an extra line to your variables.scss for the modal background.

The offending commit:
https://github.com/twbs/bootstrap/commit/f5beebe726aa8c1810015d8c62931f4559b49664#diff-a7693b847cd07d7aa4c819d11e5becc1

**Comment by ashleydw** [comment]
I have updated the github pages to use 3.3.4, are you experiencing the same problem here?: http://ashleydw.github.io/lightbox/

**Comment by upngo** [comment]
no, things look to be working properly

**Comment by jamin87** [comment]
In my case it was that they'd added that extra variable for $zindex-modal-background which is set at the original value for $zindex-modal. So both the background and the actual modal dialogue had the same z-index value.

**Comment by ashleydw** [comment]
OK, sounds like a problem with the sass stuff. Leaving open for other people, but no changes from my end
