### ISSUE TITLE
Gallery nav not working (chevrons missing, etc)

### ISSUE THREAD

**Issue by kshipp** [ashleydw/lightbox#105]
This is an awesome git, but I've found a problem using it with the current Bootstrap 3 (v3.3.2).  I don't yet know where the conflict is, but the gallery nav (the chevrons) fails to display
Is this just me?

**Comment by ashleydw** [comment]
Works fine with 3.3.2, you are probably missing the glyphicons. You can change them to whatever classes you want (font awesome etc), and set the options: `left_arrow_class` `right_arrow_class`

**Comment by kshipp** [comment]
Obviously, I'm missing something because I've beat my head against the wall enough.  I've basically taken a very simple sample of two images and I have created a jsfiddle, so you can see how the nav is not working.
https://jsfiddle.net/kshipp/2c47h46q/5/

**Comment by ashleydw** [comment]
You're markup isn't finding the parent selector. It can be a bit confusing, I'm actually taking it out soon, so for  now set the option `gallery_parent_selector: '',`

https://jsfiddle.net/2c47h46q/6/

**Comment by kshipp** [comment]
Still frustrating.  I made the changes and even gave it a div ID to refer to, even though it was a parent!  It 'navigates' now, but it there are two problems:  1)..javascript error in your code:  "Property 'handleevent is not callable', and 2)..the navigation never ends!  It's supposed to stop at the end in either direction.  It never stops.
It would be nice if you could provide a VERY simple example (not on your endless page of examples), so that it can be Easily replicated. Your examples are on a large page and impractical to extract to work with.  Creating from scratch is impossible because of all these issues.  :(

**Comment by ashleydw** [comment]
You must provide an example page - without one i cannot debug your javascript error (and that is your error, as it is not coming from the plugin).

Sorry, but the docs are very simple. The most simple example is: http://ashleydw.github.io/lightbox/#image-gallery

I think you'll be better off at stackoverflow for help

**Comment by matmattia** [comment]
The problem is that "gallery_parent_selector" isn't '' (empty string on default).

**Comment by ashleydw** [comment]
As per the docs it's `document.body`

**Comment by matmattia** [comment]
So the script is wrong, because it doesn't work without setting gallery_parent_selector = '' or gallery_parent_selector = document.body

**Comment by ashleydw** [comment]
Can you post an example page, should be done here: 

https://github.com/ashleydw/lightbox/blob/master/dist/ekko-lightbox.js#L74

**Comment by matmattia** [comment]
Now I see that you release two new versions one hour ago!
I tested the previous version. :smile: :+1:
