### ISSUE TITLE
Include a CSS class when displaying image?

### ISSUE THREAD

**Issue by wingedpig** [ashleydw/lightbox#106]
Great plugin, it's working well for me, with one issue. Because (most) browsers don't respect EXIF rotation information, I need to sometimes include various rotation CSS information when displaying photos to get them to be oriented correctly. Is there any way that I can specify a (unique per photo) CSS class to be added to the <img> tag when displayed in the lightbox?

**Comment by ashleydw** [comment]
Shouldn't you be rotating them before showing them to the user?

If any case, hook into onNavigate and do what you need there

**Comment by wingedpig** [comment]
Thanks for the pointer. I got it working that way, except that the modal dialog won't resize when the image is rotated via CSS. For my app, there are some reasons to want to rotate via CSS. But I guess I'll be rotating on the server side.

**Comment by ashleydw** [comment]
If you know how wide the images are, once rotated you can manually call `resize` https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.coffee#L297
