### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by l0010o0001l** [ashleydw/lightbox#107]
Upon lightbox execution, a ~20px height bar glides up quickly, then violently breaks the modal window open. Could we have softer transitions please? :)

**Comment by ashleydw** [comment]
That smaller box is the content you specify as the loading message, as defined here: https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.coffee#L345

You can put in any html to make it higher.

For animations, you should add custom css to `.modal-dialog` (e.g. `transition: max-width 0.5s ease`)

**Comment by l0010o0001l** [comment]
I'll play around. Thanks @ashleydw!
