### ISSUE TITLE
.modal-open class isn't removed from body from closing the modal

### ISSUE THREAD

**Issue by buzzguy** [ashleydw/lightbox#108]
Seems fine on the demo site, but on my test site - after closing the lightbox modal, and I can't scroll because the body still has '.modal-open' on the body. normal modals work as expected

**Comment by ashleydw** [comment]
demo / example?

**Comment by buzzguy** [comment]
yea sure, thanks for taking a look: potluckpicnic.com/blondes

**Comment by ashleydw** [comment]
Try using the latest versions of both jquery and bootstrap. I changed your code locally to use both the cdn versions and it works

https://code.jquery.com/
http://www.bootstrapcdn.com/
