### ISSUE TITLE
Codes on demos

### ISSUE THREAD

**Issue by tofanelli** [ashleydw/lightbox#109]
Hi!!

Nice lightbox you have here! Great job!

It's not an issue, but an implementation actually...

On your page, for each demo, mind to add the code related to it? Like in Bootstrap page, where you can see what is and how is done. 

Its better for everyone I guess! =)

Cheers =)

**Comment by ashleydw** [comment]
I will think about this, but in the mean time just view the source, it's very simple

**Comment by tofanelli** [comment]
Yeah... I do this.... its just for a time saver and understand what is happening there...  maybe it can be a codepen snippet if you like too =)

**Comment by mrnerbijay** [comment]
The plugin is really great but documentation is poor. I agree with @tofanelli . Documentation with code would be really helpful.

**Comment by ashleydw** [comment]
Feel free to submit PR's to the `gh-pages` branch 👍

**Comment by sabakilai** [comment]
Documentation is really poor. As I understood i need its js and css and do
`<a href="someurl" data-toggle="lightbox">Launch modal</a>`
But it just links me to the source of image.
Got to go - stalker your index.html with demos

**Comment by ashleydw** [comment]
@sabakilai did you read the bit under "Implementation"?

**Comment by sabakilai** [comment]
my bad

**Comment by ashleydw** [comment]
This will go in the docs for the https://github.com/ashleydw/lightbox/issues/166 branch
