### ISSUE TITLE
Update Release not picked up when installing via Bower (v3.3.0)

### ISSUE THREAD

**Issue by danbhala** [ashleydw/lightbox#112]
Hi,

love this plugin and thanks for your effort! I am trying to install your latest changes via bower.

Bower picks up the last tagged release (v3.3.0 https://github.com/ashleydw/lightbox/releases/tag/v3.3.0) but there has been one commit since then (which contains some the div.embed-responsive that surrounds youtube iframe embeds).

Any chance you could add an updated release contains the latest commit? d5f74dbab06bb14a63a74be9dacd7672c4416017

Thanks,

Dan

**Comment by ashleydw** [comment]
Isn't commit:d5f74db v3.3.0? You can see in that commit the responsive embed. It also shows in the CDN version? http://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/3.3.0/ekko-lightbox.js

**Comment by danbhala** [comment]
Its in the CDN but not in the source code of the tagged v3.3.0 release (https://github.com/ashleydw/lightbox/archive/v3.3.0.zip)

On [this page](https://github.com/ashleydw/lightbox/releases/tag/v3.3.0) it mentions there has been one commit since v3.3.0 and thats the commit with the responsive embed. Maybe it was tagged before the commit was pushed?
