### ISSUE TITLE
Fully Center the Image (Vertical / Horizontal)

### ISSUE THREAD

**Issue by stijnelskens** [ashleydw/lightbox#115]
As we can see the image is only centered horizontal but how can i fix it to center it vertical also?
I tried several things but can't fix it.

Does someone have a solution?

**Comment by ashleydw** [comment]
The modal body should resize to your image. Post a link?

**Comment by lucasprogamer** [comment]
Someone?

**Comment by ashleydw** [comment]
https://stackoverflow.com/questions/18422223/bootstrap-3-modal-vertical-position-center
