### ISSUE TITLE
scroll, resize on mobile

### ISSUE THREAD

**Issue by natsouk** [ashleydw/lightbox#116]
Hello all and thanks for your work.

On mobile (smarphone, touch screen).
when the modal is open (with ekko lightbox)
the picture scroll/resize is not user friendly ( the background move and it s really hard to resize the part of the picture we need).
Do you know how to fix it?

Thanks in advance.
Have a good day.

Regards.
Benoit.

**Comment by ashleydw** [comment]
Not sure what you mean? Please post a link

**Comment by natsouk** [comment]
For example.
Juste open this link : http://www.happyfete.com/2produit.php?rew=Costume-union-jack
Click on the main photo (with mobile)
space out/in fingers to resize de open picture.

**Comment by ashleydw** [comment]
I can zoom in fine on my mobile, but perhaps you are looking to prevent zoom? http://davidwalsh.name/zoom-mobile-browsers

Either way, if this is a problem, it's a bootstrap issue not the lightbox.

**Comment by natsouk** [comment]
That s the page zoom yes. I was thinking that it was possible to fix it on the modal picture (only on it).
THanks for your answer.
