### ISSUE TITLE
help with multiple firing events

### ISSUE THREAD

**Issue by realves** [ashleydw/lightbox#120]
Hi, i'm using your amazing plugin. I create a gallery by data attributes and using a footer with a button to submit current image file name to a PHP page by an ajax request. I have used $(documenti).on("click", "#subim", function(){//ajax call}); but if i open lightbox n times, the request is sente n times. How to fix this issue? I hope that you help me! Thanks!

**Comment by ashleydw** [comment]
see http://api.jquery.com/one/
