### ISSUE TITLE
Can't scroll after hiding lightbox

### ISSUE THREAD

**Issue by justintoth** [ashleydw/lightbox#125]
I'm using the example code for showing a single image: (ignore the knockoutjs)

```javascript
$(document).delegate('*[data-toggle="lightbox"]', 'click', function (event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });
```

```html
<a data-bind="attr: { href: photo }" data-toggle="lightbox"><img data-bind="attr: { src: photo }" /></a>
```

It works great, however after I close the modal popup by X'ing out of it or clicking off of it, scrolling no longer works on the parent page. I don't see any issues logged about this, so I feel like I'm missing something obvious here...

**Comment by ashleydw** [comment]
I can't reproduce, I would suggest posting on stackoverflow with an example page

**Comment by SiarAneas** [comment]
This is an old issue but I just stumbled over same problem: 
The reason seems to be an incompatibility with blueimp Gallery (used in my case in jQuery File Upload Basic Plus UI). After removing  
```html
<div id="blueimp-gallery">...</div>
```
the lightbox was working well.
