### ISSUE TITLE
How to add delete link/button on hidden images example

### ISSUE THREAD

**Issue by ssamran15** [ashleydw/lightbox#128]
Hi,

I want to implement delete image functionality with hidden image gallery example. please let me know is it possible to do so if yes then please guide me how?

many thanks in advance.

Samran

**Comment by ashleydw** [comment]
You can set options `footer` and `title`:

```
$(this).ekkoLightbox({
title: '',
footer: '',
});
```

**Comment by teefars** [comment]
Hi @ashleydw , I want to implement a download function to each image of my gallery. It would be something like a Download button on the footer of the modal, and each time the gallery changes image the button must also change. How can I acomplish that?
