### ISSUE TITLE
Wrong version on github

### ISSUE THREAD

**Issue by Findus23** [ashleydw/lightbox#129]
The commit https://github.com/ashleydw/lightbox/commit/d5f74dbab06bb14a63a74be9dacd7672c4416017 (Release v3.3.0) was made **after** tagging the release on git(hub).
![bildschirmfoto vom 2015-08-20 10-49-39](https://cloud.githubusercontent.com/assets/6266037/9379409/3a894612-4729-11e5-88fc-2ba77ace052e.png)
As a result you get commit https://github.com/ashleydw/lightbox/commit/54a802babab0f83733efe04cad501c72a41d638e if you download *ekko-lightbox#3.3.0* via bower, which doesn't include the most recent changes from commit https://github.com/ashleydw/lightbox/commit/d5f74dbab06bb14a63a74be9dacd7672c4416017.

**Comment by danbhala** [comment]
+1 have mentioned this before here: https://github.com/ashleydw/lightbox/issues/112

**Comment by Findus23** [comment]
Sorry for adding another issue. I must have overlooked yours.

**Comment by ashleydw** [comment]
This is grunt bump adding two commits and tagging the first, I will release manually

**Comment by ashleydw** [comment]
How's this? https://github.com/ashleydw/lightbox/releases/tag/v3.3.2

**Comment by Findus23** [comment]
Thanks for the quick fix,
it is working well for me
