### ISSUE TITLE
Images on gh-pages are not working

### ISSUE THREAD

**Issue by Findus23** [ashleydw/lightbox#130]
The examples from http://ashleydw.github.io/lightbox/ are not working because the direct links to instagram are returning "permission denied":
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>9D5A8154514AC518</RequestId>
    <HostId>
         WfQYscDaoqrrsPwg44EZ8rNssvobxMiNyx/Ni2lD8X6jfbFYeJBAmqxvLguOIjxvlhmw9qfSUow=
    </HostId>
</Error>
```

**Comment by ashleydw** [comment]
thanks for the heads up!

**Comment by Findus23** [comment]
Thanks for solving

The first image in 10 and 15 is still not working:

https://github.com/ashleydw/lightbox/blob/gh-pages/index.html#L351-L358
and
https://github.com/ashleydw/lightbox/blob/gh-pages/index.html#L383-L391

**Comment by Findus23** [comment]
In addition I just noticed that the images on the theme-pages are also not working:
http://ashleydw.github.io/lightbox/dark.html
http://ashleydw.github.io/lightbox/nyan.html
