### ISSUE TITLE
Add outline:none;  to remove the dotted preview line for Ie. 

### ISSUE THREAD

**Issue by KevinBosch** [ashleydw/lightbox#134]
Adding the outline:none; to the .ekko-lightbox-nav-overlay a will prevent the the dotted line from showing up when using Ie as a browser:

Ie do this 

![image](https://cloud.githubusercontent.com/assets/8487763/9539266/7c8aa526-4da3-11e5-9eab-4b35f4d94f37.png)

to remove this in IE

![image](https://cloud.githubusercontent.com/assets/8487763/9539305/178fe202-4da4-11e5-900f-f6e8dc844762.png)

**Comment by ashleydw** [comment]
see #132 and #121
