### ISSUE TITLE
youtube videos - allowfullscreen?

### ISSUE THREAD

**Issue by nunomira** [ashleydw/lightbox#139]
Is it possible to have allowfullscreen for youtube videos?
Couldn't find anything on this.
Thanks!

**Comment by psiico** [comment]
I found that issue today, I've fixed it. you can find a copy of it [here](http://www.uperfil.com/js/ekko-lightbox.min.js) or add a space in line 102, column 219.

**Comment by ashleydw** [comment]
What did you exactly change?

**Comment by psiico** [comment]
When I found this issue I only had the minified version, so I 'decompressed' it, searched for the error on your script, which was a problem with a missing whitespace in line 96, column 218 (my bad reporting this line in prev comment).
I'll add 2 screenshots to explain it further.

![live-version](https://cloud.githubusercontent.com/assets/14842802/10195849/988ca3f2-6787-11e5-8817-34fef0659d13.png)
![my-patch](https://cloud.githubusercontent.com/assets/14842802/10195848/98890116-6787-11e5-9869-3f88ad88ae91.png)
