### ISSUE TITLE
Modal Max-Width Not Resizing on Mobile Rotate

### ISSUE THREAD

**Issue by jessebek** [ashleydw/lightbox#143]
Browser: Safari
OS: iOS 8.1
Hardware: iPhone 5+, iPad 2+
Content: Vimeo Video

If the modal is launched while the device is in a portrait orientation, then rotated, the modal will maintain the same max-width despite the new window width, so that it appears to only span half the rotated screen. If the modal is launched while the device is in a landscape orientation, then rotated, roughly half of the modal will be visible as set with the prior max-width of the wider screen.

For my own purposes, I commented out //this.modal_dialog.css('width', 'auto').css('max-width', width_total); but this wouldn't be a solution for everyone.

**Comment by jasenkoh** [comment]
@jessebek @ashleydw I think for devices that have display smaller than `768px`, `.css('max-width', width_total)` part can be omitted. Thoughts?

**Comment by ashleydw** [comment]
This will be fixe in #166
