### ISSUE TITLE
Navigate through Instagram and YouTube lightbox content

### ISSUE THREAD

**Issue by felipevila** [ashleydw/lightbox#144]
Hi, I have a gallery of both Instagram content and YouTube videos that open in a lightbox, but navigation arrows don't seem to work. When an arrow is clicked the 'Loading...' message is shown and doesn't load the content, but when I close the modal and open another content it works fine. I need the arrows to work for navigating between instagram photos and YouTube videos. Here is my URL:

http://stage.yoplaitkids.com.php53-15.ord1-1.websitetestlink.com/

**Comment by akalata** [comment]
@felipevila have you tested on different browsers? Your link works fine for me, Firefox 41 on OSX.

**Comment by ashleydw** [comment]
Working fine here too.
