### ISSUE TITLE
Possible to bookmark Lightbox with hashtag?

### ISSUE THREAD

**Issue by scriptgeni** [ashleydw/lightbox#147]
Hi,

This plugin is great!
I was wondering if we can have a possibility to bookmark a Lightbox?
For example:
The Lightbox (modal) is open in gallery mode and a user can bookmark, So when he visits the page back later again, the modal is opened automatic?

Thanks

**Comment by ashleydw** [comment]
I won't be implementing this but you can use onNavigate to change the window.hash and then http://stackoverflow.com/questions/16113385/bookmark-modal-window-so-next-time-it-opens-if-the-page-is-open
