### ISSUE TITLE
Missing version on npm

### ISSUE THREAD

**Issue by PeterDaveHello** [ashleydw/lightbox#152]
Hi there,

Just found that there are 18 releases on GitHub - https://github.com/ashleydw/lightbox/releases, but only few releases on npm registry, the latest v3.3.3 is also missed, not sure if there is a problem with npm package?

Many thanks.

**Comment by ashleydw** [comment]
v4 going up soon

Basically, I forgot to push the npm package. Apologies for that

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
@ashleydw is it possible to push all the old versions? Thanks.
