### ISSUE TITLE
Accessing content in modal box?

### ISSUE THREAD

**Issue by Toccamonium** [ashleydw/lightbox#154]
Hi, I want to access content within the modal box like this, but it's not working, any idea?

$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
			event.preventDefault();
			var name = $(".vp-name").text();
			$(this).ekkoLightbox({
			onShown: function() {
			  var lb = $(".modal-body").find("span");
			  $(lb).text(name);	
		}
	});
});	

best regards

**Comment by ashleydw** [comment]
Look at using `onContentLoaded` instead

**Comment by Toccamonium** [comment]
Thanks for answering my question so quickly. Unfortunately <code>onContentLoaded</code> nothing happend at all. I was testing this with a simple alert("")...

I tried this but it isn't working as well:
<code>
...
$(this).ekkoLightbox({
  onContentLoaded: function() {
					var lb = this;
					$(lb.modal_content).css("background","red")
				}
			});
...
</code> 

Do you have an simple working example :)

**Comment by ashleydw** [comment]
All the docs (http://ashleydw.github.io/lightbox/) have events for `onShown` and `onContentLoaded`.
