### ISSUE TITLE
Github tag v4.0.0

### ISSUE THREAD

**Issue by Findus23** [ashleydw/lightbox#155]
There seems to be an issue with the git tag v4.0.0. Is it possible that you have commited the update after tagging the release?
Because there is no change between v3.3.3 and v4.0.0
https://github.com/ashleydw/lightbox/compare/v3.3.3...%20v4.0.0
but there is between v4.0.0 and master:
https://github.com/ashleydw/lightbox/compare/v4.0.0...master

Because of that bower is installing v4.0.0, which doesn't include the changes.

**Comment by ashleydw** [comment]
I think grunt bump messed the tag up, so I've pushed v4.0.1 manually

https://github.com/ashleydw/lightbox/compare/v3.3.3...v4.0.1

**Comment by Findus23** [comment]
Thanks for quickly solving this.
