### ISSUE TITLE
Full screen mode for videos (Vimeo)

### ISSUE THREAD

**Issue by AvenueSpaces** [ashleydw/lightbox#156]
Hi,

The full screen mode is not there (at least for Vimeo videos). I would not call it an issue, but probably something that has not been implemented. Do you plan to add this feature or do you have any hints how to enable it? 

Much appreciated,
John

**Comment by AvenueSpaces** [comment]
I see it's been fixed recently. Thanks.

**Comment by ashleydw** [comment]
Can you add a quick note on how you see it as resolved (in-case anyone else has the same issue).
