### ISSUE TITLE
"It's not working"

### ISSUE THREAD

**Issue by deeCT** [ashleydw/lightbox#158]
Hi there,
Is there much support for this? 
I see replies but theres delays on them.

Im trying to do this lightbox,

I copied the code from your gallery of images. 
Then I tried adding this to bottom of page:
$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox();
}); 

Then copied the script code from the bottom of your page including jquery links and lightbox.min.js links:

<script src="//code.jquery.com/jquery.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/3.3.0/ekko-lightbox.min.js"></script>
<script type="text/javascript">
	$(document).ready(function ($) {

				// delegate calls to data-toggle="lightbox"
				$(document).delegate('*[data-toggle="lightbox"]:not([data-gallery="navigateTo"])', 'click', function(event) {
					event.preventDefault();
					return $(this).ekkoLightbox({
						onShown: function() {
							if (window.console) {
								return console.log('onShown event fired');
							}
						},
						onContentLoaded: function() {
							if (window.console) {
								return console.log('onContentLoaded event fired');
							}
						},
						onNavigate: function(direction, itemIndex) {
							if (window.console) {
								return console.log('Navigating '+direction+'. Current item: '+itemIndex);
							}
						}
					});
				});

				//Programatically call
				$('#open-image').click(function (e) {
					e.preventDefault();
					$(this).ekkoLightbox();
				});
				$('#open-youtube').click(function (e) {
					e.preventDefault();
					$(this).ekkoLightbox();
				});

				$(document).delegate('*[data-gallery="navigateTo"]', 'click', function(event) {
					event.preventDefault();
					return $(this).ekkoLightbox({
						onShown: function() {
							var lb = this;
							$(lb.modal_content).on('click', '.modal-footer a', function(e) {
								e.preventDefault();
								lb.navigateTo(2);
							});
						}
					});
				});

			});
		
</script>
</script>
</script>

Its not working :(
What am I missing,
Theres no clear steps on your page it just dives straight into usage/implementation and I did those 2 steps.

**Comment by ashleydw** [comment]
Github issues isn't for support, use stackoverflow instead.

"Its not working" is not helpful at all. Do you have example page? Where is the rest of your code.
