### ISSUE TITLE
Add an option to skip showLoading() call

### ISSUE THREAD

**Issue by donlzx** [ashleydw/lightbox#162]
First of all, nice work!

When navigating through a gallery, I notice very fast flickering of the modal box:

* The modal box's height get smaller (the height of the loading message), briefly showing underlying page content;
* The new photo loads immediately, covering up the underlying page content.

All these happen in less than a tenth of second, since the images are already cached by the browser.  The visual effect is that underlying page content is mixed with the gallery images.

If the call to showLoading() is skipped, 

> [https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.coffee#L151](https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.coffee#L151)

the dialog box flickering does not happen.

**Comment by ashleydw** [comment]
I wonder if it couldn't be smarter and determine if the next item is already preloaded (or can't be loaded; as in videos, remote urls etc).

**Comment by ashleydw** [comment]
This is fixed in the latest https://github.com/ashleydw/lightbox/issues/166
