### ISSUE TITLE
Images for Theme examples are down

### ISSUE THREAD

**Issue by maludwig** [ashleydw/lightbox#165]
The images used for the Theme examples (ex. http://ashleydw.github.io/lightbox/dark.html) are failing to load. Like, different images just need to be referenced.

**Comment by ashleydw** [comment]
Yea you're correct, the urls have been changed. Same for the nyan theme. Feel free to PR an update to the gh-pages branch.

**Comment by maludwig** [comment]
You're expecting me to have a higher commitment to maintaining your documentation than I actually do.

**Comment by ashleydw** [comment]
ha, there's a thanks for provided a free plugin to you

**Comment by PhilJ88** [comment]
some people...

**Comment by Turqueso** [comment]
fixed on #176
