### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by tispratik** [ashleydw/lightbox#166]
I tried to use it, but am having some issues with the display.
I think BS4 does not have `data-title` and `data-footer` for modals.

**Comment by ashleydw** [comment]
I haven't tested it yet BS4 yet, but it is on my to-do

**Comment by PhilJ88** [comment]
It's working just fine for me with bootstrap 4 alpha 2. Single images and grouped galleries work great :)

The only strange issue I'm experiencing, is that some youtube video control icons (play/pause, settings, logo and fullscreen) are obscured in Firefox 44. Chrome has no such issue.

![Screenshot](http://www.pjcom.co.uk/ekko.jpg)

**Comment by PhilJ88** [comment]
Update: Ghostery seemed to be the culprit, so no worries.

**Comment by ashleydw** [comment]
For centering, you could add some custom CSS as per 

http://stackoverflow.com/questions/18422223/bootstrap-3-modal-vertical-position-center

**Comment by Phe0nix** [comment]
how to add button left and right in the footer instead of glyphicons..

**Comment by ashleydw** [comment]
@Phe0nix read the docs, and see http://ashleydw.github.io/lightbox/#navigateTo

**Comment by Phe0nix** [comment]
ashley i see the docs, but i need left and right buttons in the modal footer instead of navigation arrows..how i put buttons in the footer..i'm a beginner in JavaScript..

**Comment by Turqueso** [comment]
@Phe0nix you could use CSS to move them

**Comment by ashleydw** [comment]
Ready for bootstrap 4, this branch is a complete re-write (take note of the new documentation):

https://github.com/ashleydw/lightbox/tree/v4_0_1_jquery3_bootstrap4

Two breaking changes (in readme):

navigate_left and navigate_right functions are camelCased
gallery_parent_selector has been deprecated - document.body is default

**Comment by Metalchocobo** [comment]
Hi Ashley,
i'm reading the source of bootstrap 4's branch and i can see that you are using Glyphicons classes, but bootrstrap 4 no longer doesn't use Glyphicons. Maybe is better embed another solution.
Thank you for your work

**Comment by ashleydw** [comment]
Thanks for reminding me. I'll look into css triangles instead

**Comment by timint** [comment]
How about letting the user pass the complete HTML in the config for arrows? This is what I use:

```
$.ekkoLightbox({
  left_arrow: '<i class="fa fa-arrow-left"></i>'
});
```

**Comment by ashleydw** [comment]
`leftArrow` and `rightArrow` are now customisable html strings

**Comment by ashleydw** [comment]
https://github.com/ashleydw/lightbox/tree/v4_0_1_jquery3_bootstrap4

This has a lot of new stuff in it, only doing bug fixes in it now. Testers welcome. After testing this will be v5 for breaking changes and merged into master.

**Comment by ashleydw** [comment]
v5 has been published with this
