### ISSUE TITLE
Lightbox with youtube video: Full screen is unavailable

### ISSUE THREAD

**Issue by vickygr89** [ashleydw/lightbox#167]
I am using your light box gallery to display a you tube video, but when clicking the full screen mode I got (Full screen is unavailable). I have embedded videos in other parts of the website and are working. I also checked the ones that you have in your example and got the same message.
Any idea how can I accomplish that?
Example:
<a href="https://www.youtube.com/embed/xxxxxxxxxxxxxx&amp;rel=0" data-toggle="lightbox"><i class="fa fa-video-camera"></i>View Video</a>

Thank You so much,

Vicky.

**Comment by ashleydw** [comment]
It seems the `allowfullscreen` attribute is being combined with the class. From the docs source:

`<iframe width="560" height="315" src="//www.youtube.com/embed/k6mFF3VmVAs?badge=0&amp;autoplay=1&amp;html5=1" frameborder="0" allowfullscreenclass="embed-responsive-item"></iframe>`

I'm not sure why this is happening, it isn't like that in the source. https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.coffee#L249

To debug, I would look at modifying that.

**Comment by PhilJ88** [comment]
I encountered this and it is peculiar. I'm viewing my dev site in a frame (so I can switch responsive widths) and the fullscreen button doesn't work, but when you break out of the frame it works fine! Odd.

&fs=1 is the youtube video fullscreen parameter, but that's also the default.

Also, when you press escape out of fullscreen, the lightbox goes small and doesn't retain the original video size dimensions.

But, thanks for the great plugin!

**Comment by ashleydw** [comment]
@PhilJ88 Do you also see that it's disabled in the documentation? Does https://github.com/ashleydw/lightbox/pull/140 help your framing issues?

If you wish to test responsive widths, what about chrome's device emulation - https://developer.chrome.com/devtools/docs/device-mode ?

**Comment by PhilJ88** [comment]
http://xcartmods.com/ultra/
click the link - Launch Remote Video Modal

**Comment by ashleydw** [comment]
I found the error on the docs, it was using an older version. Please ensure you're using `4.0.1` or above
