### ISSUE TITLE
Modal over modal scroll problem

### ISSUE THREAD

**Issue by timint** [ashleydw/lightbox#169]
Opening a modal over another modal works excellent. But closing the closest returning to the modal behind messes up the page scrolling.

See video. Google .webm media can be played in VLC.

[scroll_problem.zip](https://github.com/ashleydw/lightbox/files/122568/scroll_problem.zip)

**Comment by ashleydw** [comment]
Sorry, not supported by this plugin.

See: https://github.com/twbs/bootstrap/issues/15837

From bootstrap docs:

> Multiple open modals not supported
Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.

I believe there are other bootstrap plugins that will let you do this.

**Comment by timint** [comment]
I was afraid of that but Google was not my friend. If you are available for hiring let me know. One work around could be to simply automatically close an existing modal upon starting a new.

**Comment by ashleydw** [comment]
This has stacking: http://jschr.github.io/bootstrap-modal/

**Comment by timint** [comment]
Thanks, this is very helpful as it saves me a lot of time. :)
