### ISSUE TITLE
red line in Firefox

### ISSUE THREAD

**Issue by Peter4711** [ashleydw/lightbox#170]
If you zoom an image of a group in Firefox and you click the back / next button then after clicking the clicked button appears with small red line in the middle. 

It's only in Firefox not in Chrome.

http://abload.de/img/lightboxerror2caq46.jpg
http://abload.de/img/lightboxerror155pym.jpg

Used with bootstrap v3.3.6 (CSS) and http://daneden.me/animate

**Comment by ashleydw** [comment]
https://github.com/ashleydw/lightbox/issues/134
