### ISSUE TITLE
Video not loading properly when showing next / previous Item

### ISSUE THREAD

**Issue by Wegi** [ashleydw/lightbox#180]
When a local Video (not youtube, just plain old mp4 on the server) is part of the Gallery it is only shown correctly when clicked. If you tried to load in while the gallery is open through going to the next or prebious element it loads /false.

You can hotfix this by just passing `src` to `showVideoIframe` in the `detectRemoteType` function, but then anturaly the iframe has the measurements of the prviously shown picture / video.

**Comment by ashleydw** [comment]
Please post an example
