### ISSUE TITLE
Lightbox clash with Bootstrap dropdown navigation

### ISSUE THREAD

**Issue by Kittybiccy** [ashleydw/lightbox#181]
Hi there,
I'm using the Lightbox with hidden elements which is brilliant however it is clashing with the Bootstrap dropdown nav and causing that to not work. As soon as I remove the jQuery from the page the navigation works fine. Do you have any suggestions as to what I need to chnage or an alternative piece of jQuery I could use that won't stop the navigation working? I can send you my code if that helps?
Thanks, Hannah

**Comment by ashleydw** [comment]
Post an example page.

**Comment by Kittybiccy** [comment]
Appologies for how messy everything is - here is a test link:
www.straloch.com/NEW1/accomodation-stalkers-lodge.html

**Comment by ashleydw** [comment]
You have included bootstrap javascript twice in your code

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>

<!-- lightbox -->
<script src="//code.jquery.com/jquery.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <script src="js/ekko-lightbox.js"></script>
```

Similar to http://stackoverflow.com/questions/13343947/bootstrap-dropdown-wont-work
