### ISSUE TITLE
Vimeo Videos doesn't load

### ISSUE THREAD

**Issue by weilinzung** [ashleydw/lightbox#184]
I try to use vimeo video links that input from the on the wordpress backend, but "https://vimeo.com/163003595" this type's link doesn't work, only with the "player" will work: https://player.vimeo.com/video/163003595

thanks.

**Comment by ashleydw** [comment]
Did you read the docs?

> You cannot embed Vimeo videos using the standard url (ie http://vimeo.com/80629469); you must link to the embed source (ie player.vimeo.com/video/80629469). This will mean your link url - if the JavaScript fails, will open the full screen player (try opening the first link below in a new tab); the solution to this is to set the lightbox source directly - the second link below does this.
