### ISSUE TITLE
Sliders control doesn't work after define right_arrow_class and left_arrow_class options

### ISSUE THREAD

**Issue by jehkinen** [ashleydw/lightbox#186]
I specified left arrow and right arrow classes as fa fa-chevron-left and fa fa-chevron-right but control doesn't work even if I specify default classes

**Comment by ashleydw** [comment]
Please post your code snippet.

**Comment by jehkinen** [comment]
I tried even with 'default class'    
$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox({
            'right_arrow_class' : 'glyphicon glyphicon-chevron-right',
            'left_arrow_class' : 'glyphicon glyphicon-chevron-left',
        });
    });

and the same code with fa icons 
$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox({
            'right_arrow_class' : ' fa fa-chevron-right',
            'left_arrow_class' : ' fa fa-chevron-left'
    });

Light box works fine only when I didn't specify this (left_arrow_class, right_arrow_class) options

**Comment by ashleydw** [comment]
They are used as direct CSS classes, so you need to add the fullstop at the start of them

**Comment by jehkinen** [comment]
Why it doesn't work with default icons if options has been defined?

**Comment by ashleydw** [comment]
Not sure what you mean with 'it doesn't work'. 

If you want the defaults, don't include them in the options. Otherwise you need to use css selectors, look at the source for where they're used and you'll see they're in a jquer selector. 

So .your_css_class

**Comment by ashleydw** [comment]
https://github.com/ashleydw/lightbox/issues/133
