### ISSUE TITLE
Feature Direct link to gallery image

### ISSUE THREAD

**Issue by scriptgeni** [ashleydw/lightbox#187]
Is there a way to use navigateTo to bookmark a single image? (hashtag?)
I have a gallery of images in the lightbox, but I want to know if it is possible to bookmark an image in the gallery. So when visiting that bookmark in automatically opens the lightbox with the selected image.

Thanks

**Comment by ashleydw** [comment]
You askes this before :) https://github.com/ashleydw/lightbox/issues/147

I would use the stackoverflow answer as a base, and instead of calling `modal.show`, trigger a click event on the relevant image container.

**Comment by scriptgeni** [comment]
You are right, I forgot :) I will do that anyway. 
One more question, is there a way to directly link to a number like navigateTo(2) of a gallery ?

**Comment by ashleydw** [comment]
Isn't that what you meant in your first message? Stackoverflow shows how to check the `window.hash`, then you can use `navigateTo` or a `click` to open the relevant image.
