### ISSUE TITLE
Release version with updated license info

### ISSUE THREAD

**Issue by igracia** [ashleydw/lightbox#188]
I'm trying to use the project with [webjars](http://www.webjars.org/). When adding ekko-lightbox as a Bower Webjar, I get the error the the license information is not correct, since 
```
	"license": {
		"type": "GNU GENERAL PUBLIC LICENSE",
		"url": "https://github.com/ashleydw/lightbox/blob/master/LICENSE.txt"
	},
```
is not a parseable value, while
```
"license": "MIT"
```
is. Is there going to be a 4.0.2 release anytime soon? I'd rather use the webjar, and cache the maven artifact locally than use the CDN.

**Comment by igracia** [comment]
Thanks a ton!

**Comment by ashleydw** [comment]
No worries. 

I've never used webjars but I know the CDN can take a few hours to update.

**Comment by igracia** [comment]
Yeah, that too. The good thing about using webjars with Maven is that you don't need to execute bower from the Maven build in order to get the JS dependencies for your frontend, so it's cleaner. Also, since it's a Maven artifact, it's cached locally and the dependency will be there offline.
