### ISSUE TITLE
Integration of Facebook Videos

### ISSUE THREAD

**Issue by Toccamonium** [ashleydw/lightbox#191]
Thanks for that cool and useful plugin :)

Would it be possible to integrate Facebook video support? Right now when I insert the the iframe version url, the lightbox opens, but the height is missing > video is cut off. Autoplay is also not working. 
Would be a really cool feature due to the growing impact of Facebook videos...

thx
Florian

**Comment by ashleydw** [comment]
Post a full example - either a link to your site or a jsfiddle

**Comment by Toccamonium** [comment]
here we got, scroll down the page to the video posterframes. First example ist youtube, second one ist facebook with wrong height and no autoplay http://sineos.de/index.php?id=17

**Comment by ashleydw** [comment]
I see the facebook embed. Have you looked at the FB embed documentation?:

>data-autoplay
> Automatically start playing the video when the page loads. The video will be played without sound (muted). People can turn on sound via the video player controls. This setting does not apply to mobile devices. Can be false or true.
> false

https://developers.facebook.com/docs/plugins/embedded-video-player#settings
