### ISSUE TITLE
Firefox modal doesn't show

### ISSUE THREAD

**Issue by weilinzung** [ashleydw/lightbox#192]
I try to test the Lightbox on different browsers, but on Firefox(46.01) that the modal doesn't show at all when I click the play button. on Safari and Chrome are fine.

What maybe cause this issue?

thanks.

**Comment by ashleydw** [comment]
Please provide a link or full example.

**Comment by weilinzung** [comment]
<button class="btn-margin btn-circle">
<a data-toggle="video_lightbox" class="btn cricle-play" href="<?php echo $link_url_youtube_vimeo; ?>"><span class="fa fa-play"></span></a>
</button>

I don't have the live link for now, all I can provide and I think maybe the button has problem. Only not working on Firefox now.

Thanks.

**Comment by ashleydw** [comment]
You are using invalid html5.

A very quick google: http://stackoverflow.com/questions/17253410/link-inside-a-button-not-working-in-firefox
