### ISSUE TITLE
When used with Turbolinks 5 lightbox creates multiple modal views

### ISSUE THREAD

**Issue by itspradhan** [ashleydw/lightbox#193]
First of all I really love the plugin, Thanks so much for that.

So the issue occurs when I move from first main page to another, the ekko-lightbox.min.js is loaded multiple types using turbolinks 5 because of which when I click on the image it opens multiple modals so you have to close them one by one. 

Thanks,
George

**Comment by ashleydw** [comment]
You'll be better off asking on stackoverflow as your issue isn't with the lightbox but with turbolinks.

**Comment by acegilz** [comment]
@itspradhan have you found a way to fix this?

**Comment by Genecode** [comment]
> 
> 
> @itspradhan have you found a way to fix this?

Put your ekko script in pipeline js folders (for me - app\assets\javascript\myfile.coffee)

```
$(document).on 'click', '[data-toggle="lightbox"]', (event) ->
  event.preventDefault()
  $(this).ekkoLightbox()
  return
```
