### ISSUE TITLE
Compatibility with Isotope

### ISSUE THREAD

**Issue by alahab2** [ashleydw/lightbox#200]
An optional enhancement:

I am struggling to make this plugin compatible with [http://isotope.metafizzy.co/](http://isotope.metafizzy.co/). After sorting the lightbox still shows all the images in the gallery.

I am sure I am not the only one who would like to use your Lightbox plugin with a sorting plugin.

Could you advise how to make the lightbox see only the elements that are on the screen, but not the ones that are hidden?

Maybe add it to the docs?

Would really appreciate that.

Example of the problem is [here.](http://s.codepen.io/Alahab2/debug/rLmJWW)

Cheers!

**Comment by ashleydw** [comment]
I would listen for the isotope event  `arrangeComplete` and add the `data-gallery` attribute for items that are displayed and remove it for others.

You might need to look into jquerys `removeData` function as this info is cached.

You'll be better off asking on stackoverflow as I've never used isotope.
