### ISSUE TITLE
Add youtube-nocookie supprt

### ISSUE THREAD

**Issue by hellboy81** [ashleydw/lightbox#201]
Please add support for `youtube-nocookie` to embed youtube videos with regard to European (Germany etc..) privacy protection compliance.

May be as follows:

```js
data-toggle="lightbox" data-norelated="true" data-nocookie="true"
```

See also court decision:

http://www.complexum.de/youtube-videos-ohne-setzen-von-cookies-durch-drittanbieter-auf-ihrer-webseite-einbinden/

Auto-translation EN-DE: https://goo.gl/IKc4bv

Otherwise you can get warning letters from a lawyer!

**Comment by hellboy81** [comment]
LG Düsseldorf, Urt. v.09.03.2016, Az. 12 O 151/15

**Comment by ashleydw** [comment]
Interesting, please make a PR following similar options.

**Comment by SgtOddball** [comment]
I'd be interesting in passing data-tags over but with regards to the noCookie requirement, oh boy have they still not given up on that yet?

**Comment by ashleydw** [comment]
In #166 you will be able to pass any query string to the url, but as of now, I don't plan on implementing nocookie, instead you should set your remote to the correct url.
