### ISSUE TITLE
lightbox jQuery 3.1.0 bug

### ISSUE THREAD

**Issue by Krystus** [ashleydw/lightbox#202]
Recently I found bug when using jQuery 3.1.0. Lightbox takes max width and scale up to specyfic image width in modal window. With 3.1.0 jQuery your lightbox don't add that style settings to the modal-dialog.

jQuery 2.2.4
![screen shot 2016-08-03 at 14 38 05](https://cloud.githubusercontent.com/assets/15039636/17365846/9f00916e-5988-11e6-9fe6-a91e3ac02252.png)

jQuery 3.1.0
![screen shot 2016-08-03 at 14 38 57](https://cloud.githubusercontent.com/assets/15039636/17365856/a572c15c-5988-11e6-9b82-1fd9c6a35107.png)

**Comment by lbausch** [comment]
Can't we just use ` return image.on('load', function() { .. });` ?

**Comment by ashleydw** [comment]
Can you grab the latest files from `/dist` in this branch. This is a complete re-write, please take note of the new documentation.

https://github.com/ashleydw/lightbox/tree/v4_0_1_jquery3_bootstrap4

Two breaking changes (in readme):

> navigate_left and navigate_right functions are camelCased
> gallery_parent_selector has been deprecated - document.body is default

**Comment by ashleydw** [comment]
continue this in #166

**Comment by adjohnson916** [comment]
@lbausch This bug is still present in 4.0.2 - would you consider a maintenance branch for the 4.x version and accept a pull request replacing `.load(` with `.on('load',` where appropriate?

**Comment by lbausch** [comment]
@adjohnson916 I'm not a maintainer of this project.

**Comment by ashleydw** [comment]
@adjohnson916  There's no .load() call in version 4. As you can see on the docs page, the style settings are applied http://ashleydw.github.io/lightbox/

**Comment by ashleydw** [comment]
anyone is welcome to make a 4.0.3 to fix the load bug
