### ISSUE TITLE
jQuery: load() is deprecated

### ISSUE THREAD

**Issue by lbausch** [ashleydw/lightbox#203]
Since jQuery 1.8 `load()` is deprecated (see http://api.jquery.com/load-event/) and it's removed in jQuery 3.0. This is the reason why scaling does not work with jQuery 3: https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.coffee#L292

**Comment by ashleydw** [comment]
Correct, i noticed this too in #202 

not sure about a fix, as there is no replacement. will probably have to rely on native image load

continue in #202
