### ISSUE TITLE
Images Orientation Problems

### ISSUE THREAD

**Issue by jplehmann** [ashleydw/lightbox#205]
Web page: http://www.morphmarket.com/c/reptiles/pythons/ball-pythons/36079

Click on image to bring up ekko-lightbox, and notice the orientation is different.  All other tools (browser, Facebook, and Mac Preview) render this image in portrait, but lightbox shows it in landscape.  This happens on a number of images.

Verified on Chrome and Safari.

Raw image: https://morphmarket-media.s3.amazonaws.com/media/raw_images/repterra/2016/08/20160822143729-image.jpeg

**Comment by ashleydw** [comment]
Interesting, opening the image shows the correct orientation but inspector shows it landscape:

![image](https://cloud.githubusercontent.com/assets/844437/17904342/460ef0c2-696f-11e6-98d0-ff58bc472773.png)

I think you're running into this: https://bugs.chromium.org/p/chromium/issues/detail?id=56845
http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by jplehmann** [comment]
The reason I believed it was a lightbox error is because, middle-click open image in new window (without lightbox) produces correct portrait orientation.  Left-click opening the image in lightbox produces the (wrong) landscaped orientation.

However I understand from your links that the handling for this by the browser is very flaky and that this can be explained by its weirdness.

Thanks for the links.
