### ISSUE TITLE
Force local iframe content

### ISSUE THREAD

**Issue by timint** [ashleydw/lightbox#208]
I am missing a feature to force local content as iframe rather than inline content.

This is necessary when loading isolated or printable content which cannot interfere with CSS or HTML.

My proposal is simply data-type="iframe"

I can provide the javascript code myself but I'm not too experienced with CoffeeScript.

**Comment by ashleydw** [comment]
`data-type="url"` with `data-disableExternalCheck="true"` should do it

**Comment by timint** [comment]
That didnt work for me. I tried it before creating this thread.

**Comment by frzsombor** [comment]
Didn't work for me either. I can't use this library because of this :(

**Comment by frzsombor** [comment]
@ashleydw Didn't work for me either. I can't use this library because of this :(
