### ISSUE TITLE
Close lightbox on single image by clicking/touching lightbox image

### ISSUE THREAD

**Issue by adskiremote** [ashleydw/lightbox#21]
Would it be possible to close the lightbox on single image by clicking/touching the lightbox large image?

**Comment by farmio** [comment]
it's line 58 now ->
insert
```javascript
}).click(function() {
  return _this.modal.modal('hide');
```
before line 58
```javascript
}).modal('show', options);
```

**Comment by adskiremote** [comment]
great thank you Ruben and Farmio :-)

**Comment by garbrick** [comment]
This line is no longer valid.  Can you provide an update on where to add this snippet?
