### ISSUE TITLE
Fail with an attachment response link

### ISSUE THREAD

**Issue by Soullivaneuh** [ashleydw/lightbox#211]
I use your library with a Markdown parser by automatically adding LightBox attributes on links and image.

If the user upload a file, for example, a pdf, the link goes to a `Content-Disposition: attachement` response. So the library is supposed to just launch the download with the browser.

Instead, it's trying to show the PDF content:

![image](https://cloud.githubusercontent.com/assets/1698357/18755711/83b14b6a-80ed-11e6-9688-7d2d67363ff7.png)

More weird: I copy paste the link from the production website to my local to test it, and then the download works without any content on the box.

After some investigations, it seems the bug appear **only** if the FQDN of the link is the **same** as the FQDN of the website.

Browser name and version: Chrome (Linux) - 51.0.2704.84 (64-bit)

Please tell me if you need more information.

**Comment by ashleydw** [comment]
try the newer version and make sure it's loading the content into an iframe https://github.com/ashleydw/lightbox/tree/v4_0_1_jquery3_bootstrap4
