### ISSUE TITLE
v5.0.0 - Bootstrap error: bootstrap.min.js:6 Uncaught TypeError: f[b] is not a function

### ISSUE THREAD

**Issue by TechKat** [ashleydw/lightbox#213]
jQuery: v3.1.1
Bootstrap: v3.3.7
ekko-lightbox: v5.0.0

It seems when I try and open a single image with ekko-lightbox, it throws this error when it tries to load the modal, however the backdrop, title etc work alright:
`Uncaught TypeError: f[b] is not a function`

Even dropping Bootstrap to 3.3.6 and jQuery to 2.1.1 throws this same error.

I opened a modal the usual way with Bootstrap and it works well.

![chrome_2016-09-27_09-26-25](https://cloud.githubusercontent.com/assets/6548963/18865696/80479fd8-8494-11e6-977e-c6e5742a3150.png)

**Comment by ashleydw** [comment]
Does this work for you? http://ashleydw.github.io/lightbox/#single-image

**Comment by ashleydw** [comment]
The latest relies on Bootstrap 4, for BS3 you need the old version: https://github.com/ashleydw/lightbox/releases/tag/v4.0.2

**Comment by TechKat** [comment]
Probably worth mentioning in v5.0.0 since it says 'Bootstrap 4 support', which would imply it also works alongside BS4, as well as BS3. :)

**Comment by ashleydw** [comment]
I already added it to the docs and readme 🎉
