### ISSUE TITLE
Error when using with bootstrap 3.x

### ISSUE THREAD

**Issue by ChrisPiechowicz** [ashleydw/lightbox#214]
Hi,
the plugin doesn't work with bootstrap 3,

I get this error:
Uncaught TypeError: data[option] is not a function

in this bootstrap Plugin function:
`if (typeof option == 'string') data[option](_relatedTarget)`

Bootstrap 3.3.7
ekko-lightbox 4.0.2

**Comment by ashleydw** [comment]
v4 almost definitely does work with Bootstrap 3. Do you have an example page?

**Comment by snetts** [comment]
I have tried out an implementation on version 3.3.7 of bootstrap but I am getting the error `Uncaught TypeError: f[b] is not a function`

What is the problem, could please check my code, [here](http://mexico.sebule.com/-15/posts/1-Real-Estate/2-flats-houses-for-sale/11244-Casas-Nuevas-Condado-de-Sayavedra-Estado-de-Mexico-Entrega-Inmediata.html)

Thanks.

**Comment by ashleydw** [comment]
@snetts post a minimal example, i can't figure out what i am looking at on your site

**Comment by Karlwhct** [comment]
please have a short look at
[http://www.art-in.de/share/ausstellungen/angebot.php?id=328]
the large picture didn't open. where is the problem?
ekko-lightbox 4.0.2
Bootstrap 3.0

**Comment by ashleydw** [comment]
@Karlwhct You are using the wrong version. As stated in the readme and documentation:

> Note!: This version is for Bootstrap 4, for Bootstrap 3 use the older version.

For bootstrap 3: https://github.com/ashleydw/lightbox/releases/tag/v4.0.2

**Comment by snetts** [comment]
Thanks a lot. It works fine now.

**Comment by Karlwhct** [comment]
Thanks a lot. It works fine now.

**Comment by mehmetalidumlu** [comment]
Hi,
I use bootstrap 3.3.7 and lightbox v4.0.1 in my project. But when i click on image bootstrap.js throw this exception:"0x800a01b6 - JavaScript runtime error: Object doesn't support property or method  '_handleUpdate'.
Is anybody faced this problem?
Thanks...

**Comment by ashleydw** [comment]
please post your page or jsfiddle @mehmetalidumlu

**Comment by ashleydw** [comment]
5.1.0 is BS3 compatible
