### ISSUE TITLE
Navigation arrows in modal

### ISSUE THREAD

**Issue by hrmiweby** [ashleydw/lightbox#215]
Hello, i have a problem in page http://dentprawp.hrmiweby.cz/#zubni-centrum In this page I have photoslider with arrows. It is great, but when I open photo in modal window, I need navigation arrows too.
Can you help me please? Thanks
I use this JS
 $(this).ekkoLightbox({
            loadingMessage: 'Nahrávám...',
            onNavigate: true,
              });

**Comment by ashleydw** [comment]
The example site doesn't work, please provide a minimal working example.

**Comment by hrmiweby** [comment]
Hello. Exampúle is working. Sorry for my mistake.
