### ISSUE TITLE
are you guys interested in sass css version of this project?

### ISSUE THREAD

**Issue by douglasdeodato** [ashleydw/lightbox#218]
hey guys, are you interested in a sass css version of this project? thank you.

**Comment by ashleydw** [comment]
There's no real advantage of either on a project of this size so I'm not too fussed about it to be honest; the CSS is so small, I'd rather not maintain both.

**Comment by jdavidbakr** [comment]
FWIW, I just compiled the current less into my sass project without any modifications.
