### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kbrownridge** [ashleydw/lightbox#219]
Using .NET 4.5 with Bootstrap 3.3.7 and Ekko Lightbox 4.0.2.

I have references to the CSS and JS for Ekko Lightbox in the MasterPage.

The files load, but regardless of browser, I get a compilation error: BC30035: Syntax error
It references the first 3 lines of the ekko-lightbox.min.js file.

I haven't gotten any further. Please help?

**Comment by ashleydw** [comment]
I suggest you use the CDN or the files in the /dist folder rather than compiling yourself.

**Comment by kbrownridge** [comment]
That's just it.
I'm not compiling anything.
It's VB.net, the basic .NET website template out of the box, which includes Bootstrap.
Only thing I've tried adding is Ekko Lightbox and that's the error I get.
It makes no sense.
