### ISSUE TITLE
Data-norelated tag not working

### ISSUE THREAD

**Issue by marisav** [ashleydw/lightbox#222]
I am using version 4.0.2 (May 2016 release) and am finding that the data-norelated tag does not suppress related YouTube videos.  We run Bootstrap 3, and tried version 5 plus the &rel=0, but this version of ekko-lightbox does not work on our test site with Bootstrap 3.  The live site using 4.0.2 is breslin.biz. I am aware that there may be a javascript conflict that I'm not seeing as we have a few other features on the site, but this is not the first time we've had an issue with related videos. Viewing on Mac, latest version of Chrome.

**Comment by ashleydw** [comment]
please post a minimal working example

**Comment by marisav** [comment]
Apologize. For instance, the Watch Mark's Preview Video button up top at breslin.biz is one of the many we use, implementing this code - `<a href="https://www.youtube.com/watch?v=UpgXi2X0bUg&amp;rel=0" data-toggle="lightbox" data-norelated data-width="1024"><p>Watch Mark’s Preview Video</p>
</a>` I'm using the min css and js files, implementing lightbox in the footer with `$(document).ready(function ($) {
			$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
				event.preventDefault();
				$(this).ekkoLightbox();
			});
		 });`

**Comment by marisav** [comment]
Everything else works great, it's just the norelated that's not seeming to be applied.

**Comment by ashleydw** [comment]
Looking at your website, you are using a version with no support for this (open wp-content/themes/breslin/js/ekko-lightbox-min.js and search for "norelated" gives no results).

Use the latest: https://github.com/ashleydw/lightbox/blob/v4.0.2/dist/ekko-lightbox.min.js

**Comment by marisav** [comment]
Forgive me, I need to reach out to the server admin. Though I've uploaded the correct js, it appears that it's serving a cached version (a feature the client did not communicated) still without the data-norelated.
