### ISSUE TITLE
[Feature Request] Bootstrap 3 compatibility for 5.0

### ISSUE THREAD

**Issue by timint** [ashleydw/lightbox#223]
I love the new framework of 5.0. I would love to see a port of it for Bootstrap 3 as Bootstrap 4 is till early Alpha and not fit for production use. Before production we would await the Bootstrap 4 Beta first. In computer time that could be a long way from now.

So to roll out the awesomeness of this lightbox, I want to raise opinion for a Bootstrap 3 port.

Say ":+1" if you are with me. 👍

**Comment by ashleydw** [comment]
use the v4 and change the css to look like it

https://github.com/ashleydw/lightbox/releases/tag/v4.0.2

**Comment by timint** [comment]
@ashleydw Are you saying the CSS is all that differs? Because I don't mind if it has the Bootstrap 3 look as well.

**Comment by ashleydw** [comment]
the newer version is a complete re-write but all the core functionality exists in both http://ashleydw.github.io/lightbox/bootstrap3.html

**Comment by timint** [comment]
So you are saying Ekko Lightbox 5.0 is compatible with Bootstrap 3? And the only issue is cosmetic?

**Comment by ashleydw** [comment]
they're not compatible, as the docs state: 

> Note!: This version is for Bootstrap 4, for Bootstrap 3 use the older version.

What exactly do you want that version 4 can't do but v5 can?

**Comment by timint** [comment]
I find the whole code structure of v5 great / better / more proper / easier to modify, interact, and build upon. And for projects who awaits Bootstrap 4 to go stable just won't be able to benefit from this great work until ready and transitioned.

**Comment by ashleydw** [comment]
ok. sorry no plans to re-work v4 and i think it's unwise as there are many forks from it
