### ISSUE TITLE
bower install warning message

### ISSUE THREAD

**Issue by Semen55338** [ashleydw/lightbox#224]
`bower install ekko-lightbox --save
bower not-cached    https://github.com/ashleydw/lightbox.git#*
bower resolve       https://github.com/ashleydw/lightbox.git#*
bower download      https://github.com/ashleydw/lightbox/archive/v5.0.0.tar.gz
bower extract       ekko-lightbox#* archive.tar.gz
bower invalid-meta  for:/var/folders/lw/4bpgcsqd4l9_5vnwmhsdffy80000gn/T/artem/bower/c018eb69d62130b52e552e8e3761a4db-54041-LyuYq0/bower.json
bower invalid-meta  The "main" field cannot contain minified files
bower mismatch      Version declared in the json (4.1.0) is different than the resolved one (5.0.0)
bower resolved      https://github.com/ashleydw/lightbox.git#5.0.0
bower install       ekko-lightbox#5.0.0`

**Comment by ashleydw** [comment]
hm i thought i'd removed the bower.json file but anyway, i've changed the version in it to 5.0.0, try again?
