### ISSUE TITLE
About CVEs

### ISSUE THREAD

**Issue by rpulid** [ashleydw/lightbox#230]
Is this project related with this CVE: http://www.cvedetails.com/product/30739/Lightbox-Photo-Gallery-Project-Lightbox-Photo-Gallery.html?vendor_id=15110 ?

Or do you know if there are any CVE's agaist your code?

Thanks.

**Comment by ashleydw** [comment]
No idea what that CVE is, doesn't look like this project. I haven't heard of any CVE's - to be honest, the code is so simple I'm not sure there are any. Check the source yourself for peace of mind 👍
