### ISSUE TITLE
Gallery not working with data-type URL?

### ISSUE THREAD

**Issue by BrainFeeder** [ashleydw/lightbox#231]
Hello

We are implementing this lightbox and are using it to show partial HTML views. It would be nice if we could use the data-gallery attribute to provide the lightbox with previous and next buttons to browse all partial views (which are product details in this case)

We are using the bs3 compatible version.

**Comment by ashleydw** [comment]
data-url works fine in v4, see the very bottom of this page and click "Open BBC News": http://cdn.rawgit.com/ashleydw/lightbox/e810882997264b63f1e055241f23ab22f74b3e80/examples/index.html

**Comment by BrainFeeder** [comment]
OKé, I'll give it another try.
