### ISSUE TITLE
BS4 Alpha 6 header items incorrect order

### ISSUE THREAD

**Issue by luciuschoi** [ashleydw/lightbox#235]
ekko-lightbox.min.css and ekko-lightbox.min.css.map files are not minified with updated ekko-lightbox.css file for BS4 alpha 6.

**Comment by luciuschoi** [comment]
Uncaught TypeError: this._$modal.data(...).handleUpdate is not a function
    at d.value (ekko-lightbox.js:574)
    at HTMLImageElement.e.onload (ekko-lightbox.js:520)

**Comment by ashleydw** [comment]
They are minified?

https://github.com/ashleydw/lightbox/blob/fae581a3a160c77cc8b12b3c1ce8ecc377f4961f/dist/ekko-lightbox.min.css

**Comment by luciuschoi** [comment]
It doesn't work when I open index.html file in the example directory after cloning this repo

**Comment by ashleydw** [comment]
The example works fine: https://rawgit.com/ashleydw/lightbox/master/examples/index.html

**Comment by luciuschoi** [comment]
I don't known why it doesn't work on cloning this repo.
But, Just above example shows text to be aligned right side and so it need to be updated to be aligned to left side.

**Comment by luciuschoi** [comment]
The alignment of items in flexbox mode will be controlled with flex-direction but I don't know how to fix the modal form of Bootstrap 4.

**Comment by luciuschoi** [comment]
In `ekko-lightbox.js` file, replace the header variable with the following value:
(exchange `<button>` and `<h4>` tag with each other)
```js
var header = '<div class="modal-header"' + (this._config.title || this._config.alwaysShowClose ? '' : ' style="display:none"') + '><h4 class="modal-title">' + (this._config.title || "&nbsp;") + '</h4><button type="button" class="close" data-dismiss="modal" aria-label="' + this._config.strings.close + '"><span aria-hidden="true">&times;</span></button></div>';
```			

And update styles as the following:

```css
.modal-title {
  line-height: 1.2em;
}
.modal-footer {
  justify-content: unset;
}
```

<img width="712" alt="2017-01-31_01-32-29" src="https://cloud.githubusercontent.com/assets/7693013/22431621/8174e7e8-e755-11e6-9894-1c56c7bc22fd.png">

**Comment by fizzvr** [comment]
@luciuschoi nice debug, but now we need to do a Pull Request to fix these changes. I'll do.
![image](https://cloud.githubusercontent.com/assets/3093846/22432743/e4f2e9ea-e6e3-11e6-80a2-5cacf80b13c5.png)

**Proper aligment**
