### ISSUE TITLE
Lightbox navigation not visible on videos

### ISSUE THREAD

**Issue by Turqueso** [ashleydw/lightbox#237]
When opening a video navigation arrows are not show, so on mobile, when you have a video as part of your gallery is not posible to go to the next or previous item in the gallery. The oficial demo for video gallery is an example [http://ashleydw.github.io/lightbox/#videos-gallery](http://ashleydw.github.io/lightbox/#videos-gallery)

**Comment by ashleydw** [comment]
https://github.com/ashleydw/lightbox/issues/206
https://github.com/ashleydw/lightbox/issues/102

**Comment by Turqueso** [comment]
@ashleydw bit with those alternatives still have their problems. Is there really no option where you don't loose control of the videos? maybe arrow -optional- could be outside `.ekko-lightbox-container` and inside `.modal-body`. With css you can absolute position them to look the same as now or relative position to be outside and don't mess with the videos.

**Comment by ashleydw** [comment]
if you overlay the video with the navigation arrows, how do you interact with the video?

**Comment by Turqueso** [comment]
Currently the arrows and their container are inside `ekko-lightbox-container`. The solutions in the link you shared still have some problem or another.
```
<div class="modal-body">
    <div class="ekko-lightbox-container" style="height: 315px;">
        <div class="ekko-lightbox-item fade"></div>
        <div class="ekko-lightbox-item fade in show">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe width="560" height="315" src="//www.youtube.com/embed/k6mFF3VmVAs?badge=0&amp;autoplay=1&amp;html5=1" frameborder="0" allowfullscreen="" class="embed-responsive-item"></iframe>
            </div>
        </div>
        <div class="ekko-lightbox-nav-overlay" style="display: none;"><a href="#"><span>❮</span></a><a href="#"><span>❯</span></a>
        </div>
    </div>
</div>
```
So I moved `.ekko-lightbox-nav-overlay` from `.ekko-lightbox-container` to `.modal-body` as parent and with some css show the arrow down the video so they can be used (instead of using display: none) and you can interact with the video.
```
<div class="modal-body">
    <div class="ekko-lightbox-container" style="height: 315px;">
        <div class="ekko-lightbox-item fade"></div>
        <div class="ekko-lightbox-item fade in show">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe width="560" height="315" src="//www.youtube.com/embed/k6mFF3VmVAs?badge=0&amp;autoplay=1&amp;html5=1" frameborder="0" allowfullscreen="" class="embed-responsive-item"></iframe>
            </div>
        </div>
    </div>
    <div class="ekko-lightbox-nav-overlay" style="display: none;"><a href="#"><span>❮</span></a><a href="#"><span>❯</span></a>
    </div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/4932347/22484270/da62513e-e7bd-11e6-8deb-3ec83dafb084.png)

It could be and option for the plugin arrowsPosition: top | bottom | overlay (like showArrows or alwaysShowClose). But I'm not sure if you think this proposal is a good solution. Hope this explains better my proposal.

**Comment by tumminelli** [comment]
@Turqueso Thank you for this approach. I managed to move .ekko-lightbox-nav-overlay as a child of .modal-body
Could you please provide the CSS to show the arrows underneath the video?
