### ISSUE TITLE
Hide Youtube controls

### ISSUE THREAD

**Issue by buzzguy** [ashleydw/lightbox#238]
Trying to add these parameters &amp;amp;rel=0&amp;amp;controls=0&amp;amp;showinfo=0
but are ignored.

**Comment by buzzguy** [comment]
actually, I made a quick hack and added the parameters within the plugin, but it could be a cool feature as a possible option to add into the lightbox

**Comment by ashleydw** [comment]
as @Turqueso said, all query parameters are passed into the embed so no need to extend the lightbox
