### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

### ISSUE THREAD

**Issue by asakapab0i** [ashleydw/lightbox#241]
So, you're experiencing a problem?

If you're not sure how to use the lightbox, or are experiencing a problem with it, please ask on [StackOverflow](http://stackoverflow.com/) - you will most definitely get a faster response time and it leaves this GitHub issues for actual bugs and not support questions.

If you really do think you have a bug, please:

- [ ] Provide a link to your site or a full example
- [ ] Provide screenshots where appropriate
- [ check] Browser name and version

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

When using the data-remote attribute.

**Comment by ashleydw** [comment]
This is a jquery issue, not the lightbox.

Also, next time please include the requested information
