### ISSUE TITLE
A trouble with modal ( Youtube video )

### ISSUE THREAD

**Issue by Hayko1994** [ashleydw/lightbox#259]
Does this plugin have any conflict with other libraries? I am developing bootstrap theme when I wrote only lightbox code on code pen it was worked while when I've copied it on my theme it didn't work. It doesn't show any error on console. When I click to the link modal opens but there is not any video just white clean modal. Can you help me to find the problem? Here is the link to the project. Also in the bellow is the img of the error. 
[https://github.com/Hayko1994/mobile-page-demo-fixing](url) 
![modal-trouble](https://user-images.githubusercontent.com/22639899/27702003-ab806542-5d13-11e7-95b9-7c8311cf2b36.jpg)

**Comment by ashleydw** [comment]
I tried your page, the youtube video loads fine

**Comment by Hayko1994** [comment]
I've copied only lightbox part into code pen. Thought that problem is connected with the browser while on code pen it loads perfectly. I can't find the reason of loading this modal without video :(
