### ISSUE TITLE
PDF preview ?

### ISSUE THREAD

**Issue by Ydalb** [ashleydw/lightbox#265]
Hey, I wanted to know if it could work with PDF preview ? It doesn't seem to work "out of the box", it renders the PDF "text based".

![capture d ecran 2017-08-21 a 14 55 36](https://user-images.githubusercontent.com/1888805/29520301-d2b98f26-8680-11e7-9332-731252412bd8.png)

Thank you :)

**Comment by ashleydw** [comment]
Try http://ashleydw.github.io/lightbox/#remote-content

With `data-type="url"` from http://ashleydw.github.io/lightbox/#force-type

**Comment by wreighsantos** [comment]
is this already supported? I currently am getting the same result as the above screenshot.

**Comment by MastaBaba** [comment]
Setting the data-type to "url" does not resolve this for me. I get a result like in the top image.
