### ISSUE TITLE
Is it possible to support anamorphic aspect ratios?

### ISSUE THREAD

**Issue by adampatterson** [ashleydw/lightbox#270]
A class name `responsive-16by9` is placed on the embedded content. The issue I am having though is that our video is Anamorphic.

If this is possible that would be great, Otherwise, I will handle this on our end.

![image](https://user-images.githubusercontent.com/31537/30231006-2417858e-94a6-11e7-9d54-4dda00c59d6e.png)

**Comment by ashleydw** [comment]
set `data-width` and/or `data-height` to your value
https://github.com/ashleydw/lightbox/blob/master/ekko-lightbox.js#L412
