### ISSUE TITLE
navigateTo in version 5 with Bootstrap 4?

### ISSUE THREAD

**Issue by oznorts** [ashleydw/lightbox#271]
navigateTo, which I was able to use in version 4, now doesn't work in version 5 for Bootstrap 4. Can this be added back/fixed?

**Comment by ashleydw** [comment]
`navigateTo` still exists, what does work about it? It's a core call in `navigateLeft/Right` so it should work

**Comment by oznorts** [comment]
If I do something like the below, nothing happens when #flag is clicked
  $(document).on('click', '[data-toggle="lightbox"]', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox({
            onShown: function() {
                var lb = this;
                $(lb.modal_content).on('click', '#flag', function(e) {
                    e.preventDefault();
                    lb.navigateTo(2);
                });
            }
        });
    });

**Comment by oznorts** [comment]
I figured out the problem. Instead of ```$(lb.modal_content).on('click', '#flag', function(e) { ... });``` it needed to be ```$(document).on('click', '#flag', function(e) { ... });```
