### ISSUE TITLE
Bootstrap 3 with Laravel

### ISSUE THREAD

**Issue by minedun6** [ashleydw/lightbox#279]
So I'm using laravel as a back end and I would like to use this plugin but I need my image/video to come from the backend instead of hard-coded url so what I did is the following
    `                        <a data-remote="{{ route('videos.helper') }}" data-toggle="lightbox" data-title="Flores">Launch</a>
    `

my controller returns the url properly but the problem is that instead of displaying an image/video, it just displays the url string.
Am I missing something that I should be doin ?

**Comment by ashleydw** [comment]
For support you need to post your full example.
