### ISSUE TITLE
Image is presented smaller than actual size / width attribute ignored when using remote image

### ISSUE THREAD

**Issue by bogal** [ashleydw/lightbox#280]
With the following link:

> < a data-toggle="lightbox" data-type="image" data-remote="link/to/image/"  >< i class = "fa fa-camera" style = "padding-right: 0.5em;">< / i>image filename< / a>

..the width of the image is ignored. The modal is opening with the images at a fraction of its actual size  (maybe 1/4 to 1/2). I don't know how to force the modal to open to the size of the image, but i found that setting the width attribute in the link made no difference, nor does setting the attribute during the initialision of the ekko lightbox:

> <script>
> $(document).on('click', '[data-toggle="lightbox"]', function(event) {
>     event.preventDefault();
>     $(this).ekkoLightbox({
> 		width: 1280
>     });
> });
> </script>
 - with the above link parameters, width is ignored.

Using Lightbox 4.0.2 on bootstrap 3.3 (v5.1.0 of lightbox clashes with this version of bootstrap, with an "undefined method" when loading an image. Unable to update to bootstrap 4). 
(ps, would have asked this on SO, but no idea what to tag as)

**Comment by ashleydw** [comment]
You need to post a full example, otherwise look into `data-width` and `data-height`
