### ISSUE TITLE
Error after opening lightbox

### ISSUE THREAD

**Issue by Gosokan** [ashleydw/lightbox#283]
I'm creating lightbox using this html tag to display another html page:

`<span class="pull-right"><a data-toggle="lightbox" data-remote="https://www.mysiteexample.com/description/file-description.html" >
	    <i class="fa fa-file-text" aria-hidden="true"></i></a></span>`

Lightbox can show up properly, but error after closing and opening again.

While lightbox is opening, browser console display warning "[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects "

After lightbox windows closed, I can't opening again it showing error: 
Uncaught TypeError: $(...).ekkoLightbox is not a function

Bootstrap 3.3.7 with jQuery v2.2.4

**Comment by ashleydw** [comment]
I need a full example to help
