### ISSUE TITLE
Can I grab youtube video title and place with image grabbed from youtube

### ISSUE THREAD

**Issue by justinechacko** [ashleydw/lightbox#285]
Can I grab youtube video title and place with image grabbed from youtube
I mean along with following link 

```
<a href="http://www.youtube.com/watch?v=k6mFF3VmVAs" data-toggle="lightbox" data-gallery="youtubevideos" class="col-sm-4">
    <img src="http://i1.ytimg.com/vi/yP11r5n5RNg/mqdefault.jpg" class="img-fluid">
</a>
```

Hope it is clear to you. Thanks.

**Comment by ashleydw** [comment]
If you know the title set `data-title` (see http://ashleydw.github.io/lightbox/#single-image), otherwise there's no way of getting the youtube title from the video.

**Comment by justinechacko** [comment]
https://github.com/abhinayrathore/jQuery-YouTube-Popup-Player-Plugin/blob/master/jquery.youtubepopup.js

Check this out. I think someone grabbed the title here...

**Comment by ashleydw** [comment]
You answered your question yourself :)

Take this code and put it in the `onNavigate` event

https://github.com/abhinayrathore/jQuery-YouTube-Popup-Player-Plugin/blob/master/jquery.youtubepopup.js#L129

**Comment by justinechacko** [comment]
Hi @ashleydw I am a newbie. Please share full code here. Thanks

**Comment by justinechacko** [comment]
```
onNavigate: function onNavigate() {
		$.ajax({
            url: window.location.protocol + '//query.yahooapis.com/v1/public/yql',
            data: {
                q: "select * from json where url ='http://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=" + id + "&format=json'",
                format: "json"
            },
            dataType: "jsonp",
            success: function (data) {
                if (data && data.query && data.query.results && data.query.results.json) {
                    YouTubeDialog.dialog({
					   title: data.query.results.json.title
				    });
                }
            }
        });
        },
```

Is this enough? how to get title name?
