### ISSUE TITLE
Phone back button

### ISSUE THREAD

**Issue by omdawe** [ashleydw/lightbox#286]
When a Lightbox is open and the user is on a mobile phone (Android) and if the user is trying to close the lightbox using the back button it dont close the lightbox, it go back to previous page. I understand this but i been looking at users using the lightbox and they get really confused!

**Comment by ashleydw** [comment]
I won't be adding this as it's client (android) specific, but there are plenty of examples if you look for it https://stackoverflow.com/questions/40314576/bootstrap-3-close-modal-when-pushing-browser-back-button
