### ISSUE TITLE
audio tag support

### ISSUE THREAD

**Issue by cpetro** [ashleydw/lightbox#289]
hi, 

its great that this plugin now supports locally hosted video , and mp4 embeds, and while mp3 files do work in a video tag on some browsers others do not , 

would it be possible to add support for an <audio> tag for mp3, wav, flac embeds etc.

thanks

**Comment by merglv** [comment]
I create pull request which resolve this request.
Found it here https://github.com/ashleydw/lightbox/pull/294

**Comment by ashleydw** [comment]
#294 merged into 5.4.0 👍
