### ISSUE TITLE
Fail to go from last item to first item

### ISSUE THREAD

**Issue by sanraul** [ashleydw/lightbox#299]
I dynamically created a gallery of 28 photos. The HTML code for the item was part of the page, included in the DOM:

```
<div id="templates" style="display: none">
    <a href="" data-toggle="lightbox" data-gallery="example-gallery" class="btn-thumbnail">
        <!-- the image will be added dynamically -->
   </a>
</div>
```

For the most part, lightbox works fine, but when photo #28 is reached, the "next" button does not go to photo #1, instead, it renders the template item.

It appears that instead of cycling through the specified set

```
$(document).on('click', '#container *[data-toggle="lightbox"]', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox();
});
```

It probably takes into account all items with **[data-toggle="lightbox"]** attributes, which in my case include the empty templates item. Therefore, instead of going from photo #28 to #1, it goes to the empty item with no images URL, and I end up with an js exception.

**Comment by ashleydw** [comment]
You'll need to change `data-gallery` when creating them dynamically.
