### ISSUE TITLE
Add a short description?

### ISSUE THREAD

**Issue by lucalves** [ashleydw/lightbox#306]
Good afternoon,

I have a question about lightbox. I tried to do this in every way that I know of, but I did not succeed.

How do I add a short description in each lightbox, with the option to increase and decrease the text? As if it were the native bootstrap collapse component?

**Comment by ashleydw** [comment]
You can set `data-footer` for text to in the bottom of the modal, although you won't be able to add HTML here. You probably want to modify the modal once it's open with your own JS, see `onNavigate` in the Events.
