### ISSUE TITLE
v5.3.0 - Modal dimensions not resizing properly, grey overlay present and navigation buttons hidden

### ISSUE THREAD

**Issue by danielleos** [ashleydw/lightbox#327]
Please go to https://danielleos.github.io/silverback-tkd/gallery.html and click on any of the photos to replicate - I'm using Chrome.

The issue I'm facing is that there is a grey overlay across the entire screen, the navigation buttons don't seem to appear, I can't click the screen to make the lightbox disappear and the dimensions of the modal doesn't resize according to the image. 

Screenshot attached:

<img width="1402" alt="Screenshot 2019-03-18 at 18 40 07" src="https://user-images.githubusercontent.com/16842000/54554820-5114d380-49ad-11e9-81c5-c49f743062fe.png">

Workaround for the time being is to overwrite the .modal class with a big z-index:
`.modal {
  z-index: 9999 !important;
}` 

This (rather obviously) doesn't fix the modal height dimensions though.

**Comment by danbhala** [comment]
Looks like you have custom CSS rules for that are causing the layout issues.

From line 2272 of https://danielleos.github.io/silverback-tkd/css/style.css

**Comment by danielleos** [comment]
> Looks like you have custom CSS rules for that are causing the layout issues.
> 
> From line 2272 of https://danielleos.github.io/silverback-tkd/css/style.css

@danbhala I'm not sure that class (`media-with-text img`) is causing the issue as it's not applied anywhere in the `gallery.html` file?

**Comment by danielleos** [comment]
You were right @danbhala, it was a custom css issue, just on a different line - https://github.com/danielleos/silverback-tkd/blob/6997956076faa4e44a3ea2c98d7c140894c8dac9/css/style.css#L2289

**Comment by danielleos** [comment]
You were right @danbhala about it being a custom CSS issue, just on a different line! https://github.com/danielleos/silverback-tkd/blob/6997956076faa4e44a3ea2c98d7c140894c8dac9/css/style.css#L2289
