### ISSUE TITLE
Left and right arrows are not positioned correct in Safari

### ISSUE THREAD

**Issue by akanezumi** [ashleydw/lightbox#52]
The left and the right arrow are not positioned correct when using Safari (not the mobile version). Right now, the arrows are positioned in the top left / right corner. This is also true for all the examples in the documentation.

I checked the code and narrowed it down to line 273 where the top-padding is calculated:
273: return $(this).parent().height() / 2;
Seems like "$(this).parent().height()" is always returning 0 when using Safari (checked with console.log). 

I'm using Safari 7.0.4. It's working in Chrome.

**Comment by sirnone** [comment]
I can recreate this problem with google chrome on different servers.
problem comes from function "resize", because pic is not loaded at the time "$(this).parent().height()" is called to get the height of the picture. So the funtion returns 0 all the time.

hope this will help you to find the problem

**Comment by ginarose** [comment]
Having the same issue on Safari mobile. Any updates on this fix, @ashleydw? 

After a quick glance at the script I would assume its has something to do with the image loading slower than the script that loads the height of the area the arrows are supposed to be centered within. However, I am running a mobile version of Chrome on my LG G4 (Android 5.1) and cannot replicate the issue, even with slower load times on the image.I have also tried to replicate this with Chrome's device mode.  Attached are some examples from a coworker's device for reference of the issue. Any guidance would be appreciated!

![usf1](https://cloud.githubusercontent.com/assets/4633156/12205503/1a9b814a-b609-11e5-9aa4-643a4f568c93.png)
![usf2](https://cloud.githubusercontent.com/assets/4633156/12205504/1a9e0564-b609-11e5-8680-7681b7c6172d.png)
