### ISSUE TITLE
Fix placement of left and right chevrons for mobile devices

### ISSUE THREAD

**Issue by mchiocca** [ashleydw/lightbox#59]
The placement of the left and right Glyphicon chevrons in the modal body of a Lightbox is incorrect. The chevrons appear at the very top on either side on mobile devices. The current code to calculate `padding-top` and use `.css()` in the JavaScript doesn't place the chevrons correctly on mobile devices, such as smartphones and tablets. I verified this using my iPhone 5s and iPad Air. This issue can be fixed by a simple change to the JavaScript.

In the `resize` function replace the following code
```javascript
this.lightbox_container.find('a').css('padding-top', function() {
     return $(this).parent().height() / 2;
});
```
with this one line of code instead.
```javascript
this.lightbox_container.find('a').css('vertical-align', 'middle');
```
With this change, the left and right chevrons will appear on each side, slightly toward the bottom (i.e. not exactly in the middle vertically.) However, on mobile devices, this fixes the placement, moving the chevrons from the very top downward to slightly below the middle. The chevron placement with this change is uniform across all devices, from portable devices to laptops and desktops. The chevrons appear in the same place no matter what device you are using.

Perhaps a better solution would be to remove the use of JavaScript `.css()` and instead place the CSS in the actual CSS file, (e.g. `vertical-align: middle;`) for the Glyphicon chevrons.

**Comment by ashleydw** [comment]
I agree on the css change, and so far this is working for me in FF, chrome, and safari. I would like IE tests before implementing the change. Will get to it asap

**Comment by tofanelli** [comment]
@ashleydw 

the latest version has this enhancement or is in your 2do task?? just to know =)


Cheers =)

**Comment by ashleydw** [comment]
What OS/browser are you experiencing this on? For me, iOS safari and chrome and both fine

**Comment by ashleydw** [comment]
This should be fixe in the #166 branch
