### ISSUE TITLE
URL Expand Option

### ISSUE THREAD

**Issue by cskevint** [ashleydw/lightbox#67]
Would an expand URL option be useful to you? Basically, an icon to the left of the close button that calls window.open on a provided data attributed named 'url'.

Code:
https://github.com/cskevint/lightbox/commit/3c4e7eac234a0d26f2956424d95c72d986503529

Example:
http://websites.doopr.com/nationalweb/

I can clean up the code a bit if you like it (I'm new to coffeescript).

**Comment by ashleydw** [comment]
Thanks for your input, but I think this is a design choice rather than for the plugin (you could add this via the header options).
