### ISSUE TITLE
Image doesn't show if it generate in PHP

### ISSUE THREAD

**Issue by nd3w** [ashleydw/lightbox#75]
My images don't show when they generated in PHP, instead it'd display the binary file in text.
Here's my code:

```
<a href="./img.php?file=gallery&amp;f({$record[seq].filename})" data-toggle="lightbox" data-gallery="multiimages" data-title="Caption" class="col-sm-3">
            <img src="./gallery/thumbs/{$record[seq].filename}" class="thumbnail" width="150" height="100">
</a>
```

**Comment by gbrock** [comment]
Having this problem too, and yes, my scripts are rendering the images properly.  The issue is that, without a file extension, the plugin doesn't know what to do and outputs binary text instead.

So calling ```img/1``` loads binary text **even if the server is properly serving the content type**, but ```img/1.jpg``` works.

**Comment by ashleydw** [comment]
@gbrock http://ashleydw.github.io/lightbox/#check-is-image

**Comment by gbrock** [comment]
Yep, I'm using that.  I should have been clearer: it loads the first image fine, but keying over to the next image *in a series* results in said binary code.

My exact setup:

```html
<ul class="listing-gallery">
    <li>
        <a href="/userfiles/listing/1" data-toggle="lightbox" data-gallery="img">
            <img class="img-responsive" src="/userfiles/listing/1">
        </a>
        <a href="/userfiles/listing/2" data-toggle="lightbox" data-gallery="img">
            <img class="img-responsive" src="/userfiles/listing/2">
        </a>
    </li>
</ul>
```

```js

$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox({
        type: 'image',
        gallery_parent_selector: 'document.body',
        left_arrow_class: '.fa .fa-angle-left',
        right_arrow_class: '.fa .fa-angle-right',
    });
});
```

...should I **also** have had `data-type="image"` on each item in the gallery?

**Comment by ashleydw** [comment]
> ...should I also have had data-type="image" on each item in the gallery?

yes
