### ISSUE TITLE
Add the download icon in the ekko-lightbox modal fade in

### ISSUE THREAD

**Issue by tesshsu** [ashleydw/lightbox#78]
Dear Ashleydw:

          Just I want to add the download icon (add download image function) as you click photo go to the modal page, how and where I could add the icon and function?

thanks a lot!!

**Comment by ashleydw** [comment]
You will need to set `data-footer` or `data-title`, both will accept html

**Comment by tesshsu** [comment]
Thanks!! I actually add in javascript and put tag in html, and that's work!! cheers!!
// delegate calls to data-toggle="lightbox"
		$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
			event.preventDefault();
			return $(this).ekkoLightbox({
				onShow: function(elem) {
					var html = '<button type="button" class="btn btn-info" style="padding: 10px;margin: 10px;float: left; margin-left: 50%;">safe file</button>';
					$(elem.currentTarget).find('.modal-footer').html(html);

				},
				onNavigate: function(direction, itemIndex) {
					if (window.console) {
						return console.log('Navigating '+direction+'. Current item: '+itemIndex);
					}
				}
			});
			});
		});

**Comment by edvinasurbasius** [comment]
Hello. I basically use the same code tesshsu provided, but it doesn't work. What could be the issue?

onNavigate code portion works, but button doesn't do anything : / Please help.

**Comment by tincho** [comment]
> Hello. I basically use the same code tesshsu provided, but it doesn't work. What could be the issue?

Hi there! This user doesn't exist anymore but this could be helpful to others. 
Modifying the modal contents at `onShow` event handler will probably be overriden by the plugin itself when it loads the content. 
A succesful workaround for me was delaying my change: 
```javascript
		onShow: function(ev) {
			var toAppend = $('... your text or html here ...');
			setTimeout(function() {
				$(ev.target).find('.modal-footer').append(toAppend);
			}, 1000);
		}
```
