### ISSUE TITLE
Make the modal dialog appear smoothly?

### ISSUE THREAD

**Issue by goanpeca** [ashleydw/lightbox#81]
I was wondering if it is possible to make the appearance of the modal dialog a bit smoother..

Right now the lightbox effect start, then the modal dialog appear without the content and suddenly it "jumps" to fill with the content (video/image etc..)

**Comment by ashleydw** [comment]
As the plugin uses the standard bootstrap modal, you will be able to do this with the standard bootstrap hacks. Like: http://stackoverflow.com/questions/16220795/twitter-bootstrap-modal-slide-in
