### ISSUE TITLE
Gallery Navigation Missing

### ISSUE THREAD

**Issue by andydesigns** [ashleydw/lightbox#82]
Hi,
I cant seem to get my gallery navigation arrows to display despite adding the data-gallery="multiimages" attribute.

Project is here: http://agtdesigns.co.uk/glasgowkitchens/quartz-worktops.html

Would really appreciate some help with this.

Thank you.

**Comment by ashleydw** [comment]
You're html markup is incorrect - you have two column div's within each other; either fix this or use the code suggestions in this example: http://ashleydw.github.io/lightbox/#global-galleries


```
<div class="row galleries">
<div class="col-lg-12"> <!---- delete this --->
      <div class="col-lg-3 col-md-4 col-xs-6">
```

**Comment by andydesigns** [comment]
Thanks for the help. Removing the extra div didnt make a difference, however adding the data-parent attribute has enabled the arrows but the glyphicon chevrons are not displaying. Must be a CSS issue but I cant work out whats wrong.

Ani ideas?

**Comment by dahlskebank** [comment]
![image](https://cloud.githubusercontent.com/assets/7286491/5670393/ab93ac08-977f-11e4-8f96-c2955c9d898d.png)

Obviously it's because the font isn't there... where is your font folder?

**Comment by andydesigns** [comment]
Thanks, this is resolved now.

**Comment by imshenitsky** [comment]
same problem - no errors, no navigation
