### ISSUE TITLE
Integration with Joomla 3 site

### ISSUE THREAD

**Issue by parisilocker** [ashleydw/lightbox#83]
I am a novice at JS. So be gentle. I am trying to integrate this into a Joomla 3 website I have added all the code and it seems to be loading. However when I click on item it does not pop up it just loads the page. Here is the URL: http://j.saviorlabs.com/lightbox-test

I am hoping it is something very simple.

Any help with this would be very much appreciated!

Thanks,
Paul.

**Comment by ashleydw** [comment]
You are not including the javascript on your page. console.log below:

```
 GET http://j.saviorlabs.com/templates/corporate-v1-1-4/css/bootstrap.lightbox.css 
lightbox-test:27 GET http://j.saviorlabs.com/templates/corporate-v1-1-4/js/bootstrap.lightbox.js 
lightbox-test:193 Uncaught TypeError: undefined is not a function
```

Please post further javascript questions on stackoverflow.com

**Comment by parisilocker** [comment]
Thanks for your help. I found the error, in GitHub you have the file name as ekko-lightbox.min.js but in your page http://ashleydw.github.io/lightbox/ your code has it as ekko-lightbox-min.js 

Now I am off to debug the code as it is giving me a TypeError on 	

$(document).ready(function ($) {

Really appreciate you taking the time to reply to me.

Thanks,
Paul.

**Comment by dahlskebank** [comment]
You could try changing 
$(document).ready(function ($) {
to
jQuery(document).ready(function ($) {

Although I am not expert, this is a problem I have quite often when working with WordPress.

**Comment by parisilocker** [comment]
That did it - Thanks VERY much - it works great now!
