### ISSUE TITLE
modal overlay (modal-backdrop) above all body 

### ISSUE THREAD

**Issue by fmh** [ashleydw/lightbox#85]
i can show image in modal but overlay is above all body included modal... as you see in attached print screen, but if i change the z-index of div.modal-backdrop  to 1039 it works fine.

![capture d ecran 2015-01-22 a 22 00 11](https://cloud.githubusercontent.com/assets/56861/5864496/c1d5d474-a282-11e4-8f1e-d4c0a194a75f.png)

**Comment by ashleydw** [comment]
You must have a css problem. Please use stackoverflow.com for questions like this, it's not an issue with the plugin

**Comment by fmh** [comment]
upgrade my bootstrap from 3.2 to 3.3.2 resolve this.
thx
