### ISSUE TITLE
Modal dialog behind the modal backdrop

### ISSUE THREAD

**Issue by djonatanb** [ashleydw/lightbox#86]
I had a problem with My modal appearing behind the transparent overlay (.modal-backdrop)
I fixed that with adding z-index > 1200 for the .modal-dialog class. Maybe you have something else to advise.

**Comment by ashleydw** [comment]
without an example page, no - this is an issue with your css and bootstrap, not the plugin.

see:
https://github.com/ashleydw/lightbox/issues/85
http://stackoverflow.com/questions/10636667/bootstrap-modal-appearing-under-background
