### ISSUE TITLE
auto-shrink images too big for the screen

### ISSUE THREAD

**Issue by McPringle** [ashleydw/lightbox#87]
Example: Having a 1280x960 (or 960x1280) pixel image uploaded to the server to be shown in a lightbox, but the visitor of the page as a screen resolution of 1280x800. The image is automatically scaled down to fit into the width of the lightbox, but the bottom part of the image is not visible. The lightbox should look at the hight of the image, too, so the whole image with it's lightbox fits onto screen.

Please take a look at my screenshots:
- [Lightbox with big image](https://drive.google.com/file/d/0B_z-tShPeBVabmo2SE5QMzRtdlU/view?usp=sharing)
- [Lightbox after scrolling down](https://drive.google.com/file/d/0B_z-tShPeBVaRFpBS2lMS185NGc/view?usp=sharing)

**Comment by ashleydw** [comment]
No, this plugin doesn't do that, see http://ashleydw.github.io/lightbox/#too-large
