### ISSUE TITLE
Navigation chevrons positioned too low

### ISSUE THREAD

**Issue by Toutouwai** [ashleydw/lightbox#88]
The existing code vertically positions the left/right navigation chevrons by setting padding-top:
<pre lang="javascript"><code>
this.lightbox_container.find('a').css('padding-top', function() {
    return $(this).parent().height() / 2;
});
</code></pre>
But this positions the chevron too low - the correct padding-top would be half the height of the parent minus half the line-height of the chevron.

Rather than using padding-top I think a better method would be to set the line-height to be the same as the parent height:
<pre lang="javascript"><code>
this.lightbox_container.find('a').css('line-height', function() {
	return $(this).parent().height() + 'px';
});
</code></pre>

**Comment by mchiocca** [comment]
Hello. Have you seen #59? Does you solution position the chevrons correctly on portable devices, such as smartphones and tablets? Thanks for an alternate solution to the same problem!

**Comment by ashleydw** [comment]
For me, line-height doesn't work at all. Please submit a PR with fully working code

![image](https://cloud.githubusercontent.com/assets/844437/6255377/8b27c65c-b77d-11e4-92cf-1ade6663ddf0.png)

**Comment by Toutouwai** [comment]
For some reason you're setting padding-top in the CSS as well an in the JS.
Remove "padding-top: 45%" from ".ekko-lightbox-nav-overlay a" in the CSS and setting line-height works fine.
I couldn't get #59 to work for me, but I agree that a pure CSS solution is preferable.

**Comment by ashleydw** [comment]
Grab the latest from master - it uses `line-height`. The examples page won't get updated until a new release goes out with the change. Looks good on chrome, firefox, safari, and chrome android, but needs testing in IE.

**Comment by ashleydw** [comment]
This is in master now
