### ISSUE TITLE
How to use this lightbox to display both pdfs and images?

### ISSUE THREAD

**Issue by sbha5516** [ashleydw/lightbox#89]
Hi I want to use your lightbox to display both images and pdf. Is that possible? On lightbox when I open it to display pdf, it does ; however whenever I use the arrows to move left or right and come back to the concerned pdf in the lightbox, it shows me an error message "Could not detect remote...."

Any solution /help please?

**Comment by ashleydw** [comment]
Do you have a jsfiddle or example page?
