### ISSUE TITLE
Side effect with user jquery.data()

### ISSUE THREAD

**Issue by maximo-proximo** [ashleydw/lightbox#91]
Calling `$("#element").ekkolightbox()` with element attribute : `data-remote` ekkolightbox with jquery keeps the previous data even if you change the value of the attribute `data-remote`.

To fix the problem it's necessary before calling ekklightbox to remove the previous user data stored by jquery like this code bellow:

```
$("#element").removeData();
$("#element").ekkolighbox();
```

**Comment by ashleydw** [comment]
Yea, this is a jquery caching. http://api.jquery.com/data/#data-html5

I won't change this in the source, but if you want your own version, change the `data()` calls to `attr()`

```The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery).```

**Comment by maximo-proximo** [comment]
How do you do to load images when the property data-remote is volatile (example: when it’s changed by the script) ?

Do you have an other solution ?

 

Best regards

 

De : ashleydw [mailto:notifications@github.com] 
Envoyé : jeudi 19 février 2015 16:08
À : ashleydw/lightbox
Cc : maximo-proximo
Objet : Re: [lightbox] Side effect with user jquery.data() (#91)

 

Yea, this is a jquery caching. http://api.jquery.com/data/#data-html5

I won't change this in the source, but if you want your own version, change the data() calls to attr()

The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery).

**Comment by ashleydw** [comment]
Doesn't my previous comment work?: https://github.com/ashleydw/lightbox/issues/91#issuecomment-75067061

**Comment by maximo-proximo** [comment]
Yes, but your comment is minimalist and it isn’t a good approach to resolve this behavior. ;-)

 

De : ashleydw [mailto:notifications@github.com] 
Envoyé : jeudi 19 février 2015 20:00
À : ashleydw/lightbox
Cc : maximo-proximo
Objet : Re: [lightbox] jquery.data() caching data-remote urls [fix] (#91)

 

Doesn't my previous comment work?: #91 (comment) <https://github.com/ashleydw/lightbox/issues/91#issuecomment-75067061>

**Comment by ashleydw** [comment]
Why not? What's wrong with `attr`? I think if you need more JS, stackoverflow.com will be more assistance to you.

**Comment by maximo-proximo** [comment]
Semantically the attribute data-remote indicates that it is volatile, non-persistent and it should not thus be in the jquery cache. When one changes the value of data-remote one expects that the value is taken into consideration what is not currently the case. It is thus with my meaning a problem.

 

De : ashleydw [mailto:notifications@github.com] 
Envoyé : vendredi 20 février 2015 02:31
À : ashleydw/lightbox
Cc : maximo-proximo
Objet : Re: [lightbox] jquery.data() caching data-remote urls [fix] (#91)

 

Why not? What's wrong with attr? I think if you need more JS, stackoverflow.com will be more assistance to you.

**Comment by ashleydw** [comment]
I think you should take your concerns up with jquery about `data` caching.

Another solution to your javascript problem is to set `$element.data('remote', 'value')` instead of changing the attribute, then you don't need to `removeData()`.

Sorry, but this isn't going to change
