### ISSUE TITLE
Fit image to screen height

### ISSUE THREAD

**Issue by bardo** [ashleydw/lightbox#92]
At the moment an image is only scaled if it is wider than the viewport, but this doesn't happen for height. It would be great to have the possibility to fit the image to the screen, so to avoid scrolling modals if needed.

**Comment by ashleydw** [comment]
#87 

no plans to do this at the moment

**Comment by bardo** [comment]
Not sure if I'll have the time but I'll try, thanks!

**Comment by Agasper** [comment]
@bardo i fixed, if u still need it

```
    preloadImage: function(src, onLoadShowImage) {
      var img,
        _this = this;
      img = new Image();
      if ((onLoadShowImage == null) || onLoadShowImage === true) {
        img.onload = function() {
          var image;
          var maxh = $(window).height() * 0.8; //% of screen height
          image = $('<img />');
          image.attr('src', img.src);
          image.attr('style', "max-height: " + maxh +"px");
          image.addClass('img-responsive');
          _this.lightbox_body.html(image);
          if (_this.modal_arrows) {
            _this.modal_arrows.css('display', 'block');
          }
          _this.resize(Math.min(maxh / img.height, 1) * img.width);
          return _this.options.onContentLoaded.call(_this);
        };
        img.onerror = function() {
          return _this.error('Failed to load image: ' + src);
        };
      }
      img.src = src;
      return img;
```

**Comment by bardo** [comment]
@Agasper Thanks! It looks good to me, I'll test it soon. It needs to be converted to CoffeeScript but it shouldn't be much of a hassle.

**Comment by iamgoodbytes** [comment]
Thanks @Agasper tested and works great! I was also looking for this, since many of my users are viewing the lightbox on an ipad with limited height in landscape mode.

**Comment by ivanildodias** [comment]
Firstly... Sorry. My english is very poor. :stuck_out_tongue_winking_eye:
I tested and think that is best put `0.85` in the `var maxh = $ (window) .height () * 0.85;`.
Best fills the screen.

**Comment by edalzell** [comment]
Hey @bardo, did you ever convert it to coffeescript? If so, can you please post so that I can figure out how to integrate?
