### ISSUE TITLE
Remote image modal always 560 wide

### ISSUE THREAD

**Issue by jakenoble** [ashleydw/lightbox#93]
All my remote images are loading in a modal that is 560px wide. The actual image is much larger which creates a scrolling area within the modal.

I have set _width="100%"_ and _data-width="100%"_ on the <img> but that has not helped.

**Comment by jakenoble** [comment]
There seems to be a massive difference between the way "local" images are handled and remote images. Local images displayed just fine at 100% width with an auto adjusted height. I am finding it impossible now to do the same with remote images. They appear within a much smaller iframe within the modal, rather than as an <img> in the modal.

Can this be changed? What is wrong with adding in a <img> element that points to a remote image?

**Comment by ashleydw** [comment]
I need an example to help.

**Comment by Fasse** [comment]
I have the same issue. We show a thumbnail and load the image with a link and a php script. Thats because the image lies on a htaccess folder and could not linked directly.

The modal open but the image will not be resized. Also the arrow are not centered.

You can see it here: http://spielwiese.admidio.org/adm_program/modules/photos/photos.php?pho_id=4

**Comment by ashleydw** [comment]
no response

**Comment by MedusaDelft** [comment]
@ashleydw I do have a similar (same ?) problem. I'm probably doing something wrong...
Please see: computercreations.nl/sloep/index3.html 

I'm using the latest bootstrap. Maybe my css is messing things up?
All these images have the same data-gallery. When I click on one of the first three smaller images, I can't navigate through the images. When I click on one of the bottom three images, I can navigate through the images (although the cheverons are at the top of the image).
Also, in Chrome, my background shifts after opening and closing an image.

Thank you in advance for your response!

**Comment by jakenoble** [comment]
Yes this is exactly what I experienced, remotely hosted image loading in an iFrame. I want them to load just normally like a local image.

**Comment by MedusaDelft** [comment]
@ashleydw I also noticed on safari (apple) the image breaks out of the border. The border is too small for the image (now the image is going off screen on the right.

**Comment by ashleydw** [comment]
@MedusaDelft as you are using the placeholder website, there is no extension on the url, so you must force the data type. See the docs: http://ashleydw.github.io/lightbox/#check-is-image

**Comment by jakenoble** [comment]
Ah ha perfect. Good to know, this would have been my issue too.

**Comment by MedusaDelft** [comment]
@ashleydw Thank you for your help!  I totally missed that, sorry. I guess I should sleep a bit more ;-)
