### ISSUE TITLE
Problem with http://ashleydw.github.io/lightbox/

### ISSUE THREAD

**Issue by Aymkdn** [ashleydw/lightbox#95]
Hi,

When going to http://ashleydw.github.io/lightbox/ there is a banner warning message saying : "This site is sending too much trafic to rawgit.com. Please contact its owner  and ask them to use cdn.rawgit.com instead, which has no trafic limit."

**Comment by ashleydw** [comment]
Thanks, I've removed all traces of rawgithub infacour of cdnjs.com
