### ISSUE TITLE
display text/plain contents inside a <pre> instead of a <div>

### ISSUE THREAD

**Issue by Alsciende** [ashleydw/lightbox#97]
When the content fetched has a `text/plain` Content-type, that content is injected as-is inside a `<div>` appended to `.ekko-lightbox-container`. It would be better to inject it into a `<pre>`, so that, for example, line-breaks are preserved.

**Comment by ashleydw** [comment]
There's no support for `text/plain`, only remote HTML. I also don't think that `<pre>` is a good idea for displaying text. You should return HTML; you can then wrap the content in `<pre>` if you require.
