### ISSUE TITLE
Modal size to small and do not fit to the image

### ISSUE THREAD

**Issue by Fasse** [ashleydw/lightbox#98]
We have a gallery and show thumbnail. These thumbnails are linked to an image that is loaded with a php script. Thats because the image lies on a htaccess folder and could not linked directly.

The modal open but the image will not be resized. Also the arrow are not centered.

You can see it here: http://spielwiese.admidio.org/adm_program/modules/photos/photos.php?pho_id=4

**Comment by ashleydw** [comment]
You are outputting a div not an image tag

```
view-source:http://spielwiese.admidio.org/adm_program/modules/photos/photo_presenter.php?photo_nr=1&pho_id=4
```

```html
<div style="width:640px;height:480px;"><img style="margin: auto; border: medium none; display: block; float: none; cursor: pointer;" id="cboxPhoto" src="http://spielwiese.admidio.org/adm_program/modules/photos/photo_show.php?pho_id=4&amp;photo_nr=1&amp;max_width=640&amp;max_height=480" ></div>
```

**Comment by Fasse** [comment]
Thanks for your hint.

I fix it in the script and now it works as expected.

By the way, we integrate your bootstrap enhancement in our user management software Admidio https://github.com/Admidio. Thanks for this nice tool.
